# Try to find APPLGRID
# Defines:
#   APPLGRID_FOUND
#   APPLGRID_INCLUDE_DIR
#   APPLGRID_INCLUDE_DIRS (not cached)
#   APPLGRID_LIBRARY
#   APPLGRID_LIBRARIES (not cached)
#   APPLGRID_LIBRARY_DIR (not cached)

find_library(APPLGRID_LIBRARY NAMES APPLGRID
    HINTS $ENV{APPLGRID_ROOT_DIR}/lib ${APPLGRID_ROOT_DIR}/lib)

IF(${APPLGRID_LIBRARY} MATCHES "APPLGRID_LIBRARY-NOTFOUND")
    FIND_PROGRAM(APPLGRID_CONFIG_EXECUTABLE NAMES applgrid-config
        HINTS $ENV{APPLGRID_ROOT_DIR}/bin ${APPLGRID_ROOT_DIR}/bin)
    IF(${APPLGRID_CONFIG_EXECUTABLE} MATCHES "APPLGRID_CONFIG_EXECUTABLE-NOTFOUND")
        MESSAGE(STATUS "Looking for APPLGRID... applgrid-config executable not found")
    ELSE(${APPLGRID_CONFIG_EXECUTABLE} MATCHES "APPLGRID_CONFIG_EXECUTABLE-NOTFOUND")
        MESSAGE(STATUS "Looking for APPLGRID... using applgrid-config executable")
        EXEC_PROGRAM(${APPLGRID_CONFIG_EXECUTABLE} ARGS "--prefix" OUTPUT_VARIABLE APPLGRID_PREFIX)
        find_library(APPLGRID_LIBRARY NAMES APPLgrid libAPPLgrid PATHS ${APPLGRID_PREFIX}/lib)
    ENDIF(${APPLGRID_CONFIG_EXECUTABLE} MATCHES "APPLGRID_CONFIG_EXECUTABLE-NOTFOUND")
ENDIF(${APPLGRID_LIBRARY} MATCHES "APPLGRID_LIBRARY-NOTFOUND")

find_path(APPLGRID_INCLUDE_DIR appl_grid/appl_grid.h
    HINTS $ENV{APPLGRID_ROOT_DIR}/include ${APPLGRID_ROOT_DIR}/include ${APPLGRID_PREFIX}/include)

mark_as_advanced(APPLGRID_LIBRARY APPLGRID_INCLUDE_DIR)

# handle QUIETLY and REQUIRED arguments and set APPLGRID_FOUND to TRUE if
# all listed variables are TRUE
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(APPLGRID DEFAULT_MSG APPLGRID_INCLUDE_DIR APPLGRID_LIBRARY)

set(APPLGRID_LIBRARIES ${APPLGRID_LIBRARY})
get_filename_component(APPLGRID_LIBRARY_DIRS ${APPLGRID_LIBRARY} PATH)

set(APPLGRID_INCLUDE_DIRS ${APPLGRID_INCLUDE_DIR})

mark_as_advanced(APPLGRID_FOUND)
