# Try to find FASTNLO
# Defines:
#   FASTNLO_FOUND
#   FASTNLO_INCLUDE_DIR
#   FASTNLO_INCLUDE_DIRS (not cached)
#   FASTNLO_LIBRARY
#   FASTNLO_LIBRARIES (not cached)
#   FASTNLO_LIBRARY_DIR (not cached)

find_library(FASTNLO_LIBRARY NAMES FASTNLO
    HINTS $ENV{FASTNLO_ROOT_DIR}/lib ${FASTNLO_ROOT_DIR}/lib)

IF(${FASTNLO_LIBRARY} MATCHES "FASTNLO_LIBRARY-NOTFOUND")
    FIND_PROGRAM(FASTNLO_CONFIG_EXECUTABLE NAMES fnlo-tk-config
        HINTS $ENV{FASTNLO_ROOT_DIR}/bin ${FASTNLO_ROOT_DIR}/bin)
    IF(${FASTNLO_CONFIG_EXECUTABLE} MATCHES "FASTNLO_CONFIG_EXECUTABLE-NOTFOUND")
        MESSAGE(STATUS "Looking for FASTNLO... fnlo-tk-config executable not found")
    ELSE(${FASTNLO_CONFIG_EXECUTABLE} MATCHES "FASTNLO_CONFIG_EXECUTABLE-NOTFOUND")
        MESSAGE(STATUS "Looking for FASTNLO... using fnlo-tk-config executable")
        EXEC_PROGRAM(${FASTNLO_CONFIG_EXECUTABLE} ARGS "--prefix" OUTPUT_VARIABLE FASTNLO_PREFIX)
        find_library(FASTNLO_LIBRARY NAMES fastnlotoolkit libfastnlotoolkit PATHS ${FASTNLO_PREFIX}/lib)
    ENDIF(${FASTNLO_CONFIG_EXECUTABLE} MATCHES "FASTNLO_CONFIG_EXECUTABLE-NOTFOUND")
ENDIF(${FASTNLO_LIBRARY} MATCHES "FASTNLO_LIBRARY-NOTFOUND")

find_path(FASTNLO_INCLUDE_DIR fastnlotk/fastNLOReader.h
    HINTS $ENV{FASTNLO_ROOT_DIR}/include ${FASTNLO_ROOT_DIR}/include ${FASTNLO_PREFIX}/include)

mark_as_advanced(FASTNLO_LIBRARY FASTNLO_INCLUDE_DIR)

# handle QUIETLY and REQUIRED arguments and set FASTNLO_FOUND to TRUE if
# all listed variables are TRUE
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(FASTNLO DEFAULT_MSG FASTNLO_INCLUDE_DIR FASTNLO_LIBRARY)

set(FASTNLO_LIBRARIES ${FASTNLO_LIBRARY})
get_filename_component(FASTNLO_LIBRARY_DIRS ${FASTNLO_LIBRARY} PATH)

set(FASTNLO_INCLUDE_DIRS ${FASTNLO_INCLUDE_DIR})

mark_as_advanced(FASTNLO_FOUND)
