#define TreeForWasym_cxx
#include "Wasymmetry/TreeForWasym.h"

using namespace std;

TreeForWasym::TreeForWasym()
{
 Init();
}

TreeForWasym::~TreeForWasym()
{

}

void TreeForWasym::ConfigFile(int NFilePerJob, int iRound)
{
 FirstFile = iRound * NFilePerJob;
 EndFile = (iRound + 1) * NFilePerJob;
 
 if(EndFile >= RootNames.size()) EndFile = RootNames.size();
 
 for(int i = FirstFile; i < EndFile; i++){
   rootfile[i] = new TFile(RootNames.at(i));
   SetBranch(i);

   nchannel = GetRootType(RootNames.at(i));
   RootTypes.push_back(nchannel);
   CrossSections.push_back(CrossSection);
   SumOfWeights.push_back(SumOfWeight);
 }
}

void TreeForWasym::ConfigFile(int ifile)
{
 OneFilePerJob = true;
 FirstFile = 0;
 EndFile = 1;

 rootfile[0] = new TFile(RootNames.at(ifile));
 SetBranch(0);

 nchannel = GetRootType(RootNames.at(ifile));

 RootTypes.clear();
 CrossSections.clear();
 SumOfWeights.clear();

 RootTypes.push_back(nchannel);
 CrossSections.push_back(CrossSection);
 SumOfWeights.push_back(SumOfWeight);

// cout<<"Open the file: "<<RootNames.at(ifile)<<endl;
// cout<<CrossSections.at(0)<<" "<<SumOfWeights.at(0)<<" "<<CrossSections.at(0) / SumOfWeights.at(0)<<endl;
}

void TreeForWasym::InputFile(vector<TString> RootNames)
{
 this->RootNames = RootNames;

}

int TreeForWasym::GetRootType(TString RootName)
{
 int nchannel;

 if(RootName.Contains("_361100_")) nchannel = 361100;
 if(RootName.Contains("_361101_")) nchannel = 361101;
 if(RootName.Contains("_361102_")) nchannel = 361102;
 if(RootName.Contains("_361103_")) nchannel = 361103;
 if(RootName.Contains("_361104_")) nchannel = 361104;
 if(RootName.Contains("_361105_")) nchannel = 361105;
 if(RootName.Contains("_361106_")) nchannel = 361106;
 if(RootName.Contains("_361107_")) nchannel = 361107;
 if(RootName.Contains("_361108_")) nchannel = 361108;
 if(RootName.Contains("_363356_")) nchannel = 363356;
 if(RootName.Contains("_363358_")) nchannel = 363358;
 if(RootName.Contains("_363359_")) nchannel = 363359;
 if(RootName.Contains("_363360_")) nchannel = 363360;
 if(RootName.Contains("_363489_")) nchannel = 363489;
 if(RootName.Contains("_364250_")) nchannel = 364250;
 if(RootName.Contains("_364253_")) nchannel = 364253;
 if(RootName.Contains("_364254_")) nchannel = 364254;
 if(RootName.Contains("_364255_")) nchannel = 364255;
 if(RootName.Contains("_410013_")) nchannel = 410013;
 if(RootName.Contains("_410014_")) nchannel = 410014;
 if(RootName.Contains("_410470_")) nchannel = 410470;
 if(RootName.Contains("_410642_")) nchannel = 410642;
 if(RootName.Contains("_410643_")) nchannel = 410643;
 if(RootName.Contains("_410644_")) nchannel = 410644;
 if(RootName.Contains("_410645_")) nchannel = 410645;
 if(RootName.Contains("Data17") || RootName.Contains("Data18")) nchannel = -1;

 this->CrossSection = GetCrossSection(nchannel);
 this->SumOfWeight = GetSumOfWeight(nchannel);

 return nchannel;
}

void TreeForWasym::SetBranch(int ifile)
{
   fChain[ifile] = (TTree *)rootfile[ifile]->Get("Tree");

   fChain[ifile]->SetBranchAddress("EventWeight_gen", &EventWeight_gen, &b_EventWeight_gen);
   fChain[ifile]->SetBranchAddress("EventWeight_pu", &EventWeight_pu, &b_EventWeight_pu);
   fChain[ifile]->SetBranchAddress("EventWeight_vertex", &EventWeight_vertex, &b_EventWeight_vertex);
   fChain[ifile]->SetBranchAddress("RunNumber", &RunNumber, &b_RunNumber);
   fChain[ifile]->SetBranchAddress("EvtNumber", &EvtNumber, &b_EvtNumber);
   fChain[ifile]->SetBranchAddress("vxp_z0", &vxp_z0, &b_vxp_z0);
   fChain[ifile]->SetBranchAddress("npv", &npv, &b_npv);
   fChain[ifile]->SetBranchAddress("nTracksPV", &nTracksPV, &b_nTracksPV);
   fChain[ifile]->SetBranchAddress("nintime", &nintime, &b_nintime);
   fChain[ifile]->SetBranchAddress("bcid", &bcid, &b_bcid);
   fChain[ifile]->SetBranchAddress("lbn", &lbn, &b_lbn);
   fChain[ifile]->SetBranchAddress("actual_mu", &actual_mu, &b_actual_mu);
   fChain[ifile]->SetBranchAddress("mcChannelNumber", &mcChannelNumber, &b_mcChannelNumber);
   fChain[ifile]->SetBranchAddress("nHadPart", &nHadPart, &b_nHadPart);
   fChain[ifile]->SetBranchAddress("nHadChargedPart", &nHadChargedPart, &b_nHadChargedPart);
   fChain[ifile]->SetBranchAddress("sumPtHadPart", &sumPtHadPart, &b_sumPtHadPart);
   fChain[ifile]->SetBranchAddress("sumPtChargedPart", &sumPtChargedPart, &b_sumPtChargedPart);
   fChain[ifile]->SetBranchAddress("passTrigger_el", &passTrigger_el, &b_passTrigger_el);
   fChain[ifile]->SetBranchAddress("passTrigger_mu", &passTrigger_mu, &b_passTrigger_mu);
   fChain[ifile]->SetBranchAddress("jet_pt", &jet_pt, &b_jet_pt);
   fChain[ifile]->SetBranchAddress("jet_eta", &jet_eta, &b_jet_eta);
   fChain[ifile]->SetBranchAddress("jet_phi", &jet_phi, &b_jet_phi);
   fChain[ifile]->SetBranchAddress("mu_pt", &mu_pt, &b_mu_pt);
   fChain[ifile]->SetBranchAddress("mu_eta", &mu_eta, &b_mu_eta);
   fChain[ifile]->SetBranchAddress("mu_phi", &mu_phi, &b_mu_phi);
   fChain[ifile]->SetBranchAddress("mu_charge", &mu_charge, &b_mu_charge);
   fChain[ifile]->SetBranchAddress("mu_d0sig", &mu_d0sig, &b_mu_d0sig);
   fChain[ifile]->SetBranchAddress("mu_delta_z0", &mu_delta_z0, &b_mu_delta_z0);
   fChain[ifile]->SetBranchAddress("mu_isTight", &mu_isTight, &b_mu_isTight);
   fChain[ifile]->SetBranchAddress("mu_trigMatch", &mu_trigMatch, &b_mu_trigMatch);
   fChain[ifile]->SetBranchAddress("mu_inrecoil", &mu_inrecoil, &b_mu_inrecoil);
   fChain[ifile]->SetBranchAddress("mu_isolation_ptcone20", &mu_isolation_ptcone20, &b_mu_isolation_ptcone20);
   fChain[ifile]->SetBranchAddress("mu_isolation_ptvarcone20", &mu_isolation_ptvarcone20, &b_mu_isolation_ptvarcone20);
   fChain[ifile]->SetBranchAddress("mu_isolation_ptvarcone30", &mu_isolation_ptvarcone30, &b_mu_isolation_ptvarcone30);
   fChain[ifile]->SetBranchAddress("mu_isolation_ptvarcone40", &mu_isolation_ptvarcone40, &b_mu_isolation_ptvarcone40);
   fChain[ifile]->SetBranchAddress("mu_isolation_topoetcone20", &mu_isolation_topoetcone20, &b_mu_isolation_topoetcone20);
   fChain[ifile]->SetBranchAddress("mu_isolation_topoetcone30", &mu_isolation_topoetcone30, &b_mu_isolation_topoetcone30);
   fChain[ifile]->SetBranchAddress("mu_isolation_topoetcone40", &mu_isolation_topoetcone40, &b_mu_isolation_topoetcone40);
   fChain[ifile]->SetBranchAddress("mu_isIsolated", &mu_isIsolated, &b_mu_isIsolated);
   fChain[ifile]->SetBranchAddress("mu_corrected_pt", &mu_corrected_pt, &b_mu_corrected_pt);
   fChain[ifile]->SetBranchAddress("mu_recosf", &mu_recosf, &b_mu_recosf);
   fChain[ifile]->SetBranchAddress("mu_recomceff", &mu_recomceff, &b_mu_recomceff);
   fChain[ifile]->SetBranchAddress("mu_isosf", &mu_isosf, &b_mu_isosf);
   fChain[ifile]->SetBranchAddress("mu_isomceff", &mu_isomceff, &b_mu_isomceff);
   fChain[ifile]->SetBranchAddress("mu_ttvasf", &mu_ttvasf, &b_mu_ttvasf);
   fChain[ifile]->SetBranchAddress("mu_ttvamceff", &mu_ttvamceff, &b_mu_ttvamceff);
   fChain[ifile]->SetBranchAddress("mu_trigsf", &mu_trigsf, &b_mu_trigsf);
   fChain[ifile]->SetBranchAddress("mu_trigmceff", &mu_trigmceff, &b_mu_trigmceff);
   fChain[ifile]->SetBranchAddress("mu_syspt_MUON_ID__1down", &mu_syspt_MUON_ID__1down, &b_mu_syspt_MUON_ID__1down);
   fChain[ifile]->SetBranchAddress("mu_syspt_MUON_ID__1up", &mu_syspt_MUON_ID__1up, &b_mu_syspt_MUON_ID__1up);
   fChain[ifile]->SetBranchAddress("mu_syspt_MUON_MS__1down", &mu_syspt_MUON_MS__1down, &b_mu_syspt_MUON_MS__1down);
   fChain[ifile]->SetBranchAddress("mu_syspt_MUON_MS__1up", &mu_syspt_MUON_MS__1up, &b_mu_syspt_MUON_MS__1up);
   fChain[ifile]->SetBranchAddress("mu_syspt_MUON_SAGITTA_RESBIAS__1down", &mu_syspt_MUON_SAGITTA_RESBIAS__1down, &b_mu_syspt_MUON_SAGITTA_RESBIAS__1down);
   fChain[ifile]->SetBranchAddress("mu_syspt_MUON_SAGITTA_RESBIAS__1up", &mu_syspt_MUON_SAGITTA_RESBIAS__1up, &b_mu_syspt_MUON_SAGITTA_RESBIAS__1up);
   fChain[ifile]->SetBranchAddress("mu_syspt_MUON_SAGITTA_RHO__1down", &mu_syspt_MUON_SAGITTA_RHO__1down, &b_mu_syspt_MUON_SAGITTA_RHO__1down);
   fChain[ifile]->SetBranchAddress("mu_syspt_MUON_SAGITTA_RHO__1up", &mu_syspt_MUON_SAGITTA_RHO__1up, &b_mu_syspt_MUON_SAGITTA_RHO__1up);
   fChain[ifile]->SetBranchAddress("mu_syspt_MUON_SCALE__1down", &mu_syspt_MUON_SCALE__1down, &b_mu_syspt_MUON_SCALE__1down);
   fChain[ifile]->SetBranchAddress("mu_syspt_MUON_SCALE__1up", &mu_syspt_MUON_SCALE__1up, &b_mu_syspt_MUON_SCALE__1up);
   fChain[ifile]->SetBranchAddress("mu_recosf_MuRecoSys_uncorr_up", &mu_recosf_MuRecoSys_uncorr_up, &b_mu_recosf_MuRecoSys_uncorr_up);
   fChain[ifile]->SetBranchAddress("mu_recosf_MuRecoSys_uncorr_down", &mu_recosf_MuRecoSys_uncorr_down, &b_mu_recosf_MuRecoSys_uncorr_down);
   fChain[ifile]->SetBranchAddress("mu_recosf_MuRecoSys_uncorr_BinNumber", &mu_recosf_MuRecoSys_uncorr_BinNumber, &b_mu_recosf_MuRecoSys_uncorr_BinNumber);
   fChain[ifile]->SetBranchAddress("mu_recosf_MuRecoSys_uncorr_MaxBinNumber", &mu_recosf_MuRecoSys_uncorr_MaxBinNumber, &b_mu_recosf_MuRecoSys_uncorr_MaxBinNumber);
   fChain[ifile]->SetBranchAddress("mu_recosf_MuRecoSys_corr_QCDTEMPLATE_down", &mu_recosf_MuRecoSys_corr_QCDTEMPLATE_down, &b_mu_recosf_MuRecoSys_corr_QCDTEMPLATE_down);
   fChain[ifile]->SetBranchAddress("mu_recosf_MuRecoSys_corr_BKGFRACTION_down", &mu_recosf_MuRecoSys_corr_BKGFRACTION_down, &b_mu_recosf_MuRecoSys_corr_BKGFRACTION_down);
   fChain[ifile]->SetBranchAddress("mu_recosf_MuRecoSys_corr_LUMIUNCERT_down", &mu_recosf_MuRecoSys_corr_LUMIUNCERT_down, &b_mu_recosf_MuRecoSys_corr_LUMIUNCERT_down);
   fChain[ifile]->SetBranchAddress("mu_recosf_MuRecoSys_corr_MCXSEC_down", &mu_recosf_MuRecoSys_corr_MCXSEC_down, &b_mu_recosf_MuRecoSys_corr_MCXSEC_down);
   fChain[ifile]->SetBranchAddress("mu_recosf_MuRecoSys_corr_SUPRESSIONSCALE_down", &mu_recosf_MuRecoSys_corr_SUPRESSIONSCALE_down, &b_mu_recosf_MuRecoSys_corr_SUPRESSIONSCALE_down);
   fChain[ifile]->SetBranchAddress("mu_recosf_MuRecoSys_corr_QCDTEMPLATE_up", &mu_recosf_MuRecoSys_corr_QCDTEMPLATE_up, &b_mu_recosf_MuRecoSys_corr_QCDTEMPLATE_up);
   fChain[ifile]->SetBranchAddress("mu_recosf_MuRecoSys_corr_BKGFRACTION_up", &mu_recosf_MuRecoSys_corr_BKGFRACTION_up, &b_mu_recosf_MuRecoSys_corr_BKGFRACTION_up);
   fChain[ifile]->SetBranchAddress("mu_recosf_MuRecoSys_corr_LUMIUNCERT_up", &mu_recosf_MuRecoSys_corr_LUMIUNCERT_up, &b_mu_recosf_MuRecoSys_corr_LUMIUNCERT_up);
   fChain[ifile]->SetBranchAddress("mu_recosf_MuRecoSys_corr_MCXSEC_up", &mu_recosf_MuRecoSys_corr_MCXSEC_up, &b_mu_recosf_MuRecoSys_corr_MCXSEC_up);
   fChain[ifile]->SetBranchAddress("mu_recosf_MuRecoSys_corr_SUPRESSIONSCALE_up", &mu_recosf_MuRecoSys_corr_SUPRESSIONSCALE_up, &b_mu_recosf_MuRecoSys_corr_SUPRESSIONSCALE_up);
   fChain[ifile]->SetBranchAddress("mu_recosf_MuRecoSys_corr_MATCHING_SYM_up", &mu_recosf_MuRecoSys_corr_MATCHING_SYM_up, &b_mu_recosf_MuRecoSys_corr_MATCHING_SYM_up);
   fChain[ifile]->SetBranchAddress("mu_recosf_MuRecoSys_corr_TRUTH_SYM_up", &mu_recosf_MuRecoSys_corr_TRUTH_SYM_up, &b_mu_recosf_MuRecoSys_corr_TRUTH_SYM_up);
   fChain[ifile]->SetBranchAddress("mu_recosf_MuRecoSys_corr_MATCHING_SYM_down", &mu_recosf_MuRecoSys_corr_MATCHING_SYM_down, &b_mu_recosf_MuRecoSys_corr_MATCHING_SYM_down);
   fChain[ifile]->SetBranchAddress("mu_recosf_MuRecoSys_corr_TRUTH_SYM_down", &mu_recosf_MuRecoSys_corr_TRUTH_SYM_down, &b_mu_recosf_MuRecoSys_corr_TRUTH_SYM_down);
   fChain[ifile]->SetBranchAddress("mu_recosf_MuRecoSys_corr_HIGHTOLOWEXTRAPOLATION_up", &mu_recosf_MuRecoSys_corr_HIGHTOLOWEXTRAPOLATION_up, &b_mu_recosf_MuRecoSys_corr_HIGHTOLOWEXTRAPOLATION_up);
   fChain[ifile]->SetBranchAddress("mu_recosf_MuRecoSys_corr_HIGHTOLOWEXTRAPOLATION_down", &mu_recosf_MuRecoSys_corr_HIGHTOLOWEXTRAPOLATION_down, &b_mu_recosf_MuRecoSys_corr_HIGHTOLOWEXTRAPOLATION_down);
   fChain[ifile]->SetBranchAddress("mu_recosf_MuRecoSys_corr_PtDEPENDENCY_up", &mu_recosf_MuRecoSys_corr_PtDEPENDENCY_up, &b_mu_recosf_MuRecoSys_corr_PtDEPENDENCY_up);
   fChain[ifile]->SetBranchAddress("mu_recosf_MuRecoSys_corr_PtDEPENDENCY_down", &mu_recosf_MuRecoSys_corr_PtDEPENDENCY_down, &b_mu_recosf_MuRecoSys_corr_PtDEPENDENCY_down);
   fChain[ifile]->SetBranchAddress("mu_isosf_MuIsoSys_uncorr_up", &mu_isosf_MuIsoSys_uncorr_up, &b_mu_isosf_MuIsoSys_uncorr_up);
   fChain[ifile]->SetBranchAddress("mu_isosf_MuIsoSys_uncorr_down", &mu_isosf_MuIsoSys_uncorr_down, &b_mu_isosf_MuIsoSys_uncorr_down);
   fChain[ifile]->SetBranchAddress("mu_isosf_MuIsoSys_uncorr_BinNumber", &mu_isosf_MuIsoSys_uncorr_BinNumber, &b_mu_isosf_MuIsoSys_uncorr_BinNumber);
   fChain[ifile]->SetBranchAddress("mu_isosf_MuIsoSys_uncorr_MaxBinNumber", &mu_isosf_MuIsoSys_uncorr_MaxBinNumber, &b_mu_isosf_MuIsoSys_uncorr_MaxBinNumber);
   fChain[ifile]->SetBranchAddress("mu_isosf_MuIsoSys_corr_eta_up", &mu_isosf_MuIsoSys_corr_eta_up, &b_mu_isosf_MuIsoSys_corr_eta_up);
   fChain[ifile]->SetBranchAddress("mu_isosf_MuIsoSys_corr_eta_down", &mu_isosf_MuIsoSys_corr_eta_down, &b_mu_isosf_MuIsoSys_corr_eta_down);
   fChain[ifile]->SetBranchAddress("mu_isosf_MuIsoSys_corr_mass_up", &mu_isosf_MuIsoSys_corr_mass_up, &b_mu_isosf_MuIsoSys_corr_mass_up);
   fChain[ifile]->SetBranchAddress("mu_isosf_MuIsoSys_corr_mass_down", &mu_isosf_MuIsoSys_corr_mass_down, &b_mu_isosf_MuIsoSys_corr_mass_down);
   fChain[ifile]->SetBranchAddress("mu_isosf_MuIsoSys_corr_tpdR_up", &mu_isosf_MuIsoSys_corr_tpdR_up, &b_mu_isosf_MuIsoSys_corr_tpdR_up);
   fChain[ifile]->SetBranchAddress("mu_isosf_MuIsoSys_corr_tpdR_down", &mu_isosf_MuIsoSys_corr_tpdR_down, &b_mu_isosf_MuIsoSys_corr_tpdR_down);
   fChain[ifile]->SetBranchAddress("mu_isosf_MuIsoSys_corr_isoBkg_up", &mu_isosf_MuIsoSys_corr_isoBkg_up, &b_mu_isosf_MuIsoSys_corr_isoBkg_up);
   fChain[ifile]->SetBranchAddress("mu_isosf_MuIsoSys_corr_isoBkg_down", &mu_isosf_MuIsoSys_corr_isoBkg_down, &b_mu_isosf_MuIsoSys_corr_isoBkg_down);
   fChain[ifile]->SetBranchAddress("mu_isosf_MuIsoSys_corr_probeQ_up", &mu_isosf_MuIsoSys_corr_probeQ_up, &b_mu_isosf_MuIsoSys_corr_probeQ_up);
   fChain[ifile]->SetBranchAddress("mu_isosf_MuIsoSys_corr_probeQ_down", &mu_isosf_MuIsoSys_corr_probeQ_down, &b_mu_isosf_MuIsoSys_corr_probeQ_down);
   fChain[ifile]->SetBranchAddress("mu_isosf_MuIsoSys_corr_tagIsol_up", &mu_isosf_MuIsoSys_corr_tagIsol_up, &b_mu_isosf_MuIsoSys_corr_tagIsol_up);
   fChain[ifile]->SetBranchAddress("mu_isosf_MuIsoSys_corr_tagIsol_down", &mu_isosf_MuIsoSys_corr_tagIsol_down, &b_mu_isosf_MuIsoSys_corr_tagIsol_down);
   fChain[ifile]->SetBranchAddress("mu_isosf_MuIsoSys_corr_dRmuj_up", &mu_isosf_MuIsoSys_corr_dRmuj_up, &b_mu_isosf_MuIsoSys_corr_dRmuj_up);
   fChain[ifile]->SetBranchAddress("mu_isosf_MuIsoSys_corr_dRmuj_down", &mu_isosf_MuIsoSys_corr_dRmuj_down, &b_mu_isosf_MuIsoSys_corr_dRmuj_down);
   fChain[ifile]->SetBranchAddress("mu_ttvasf_MuTTVASys_uncorr_up", &mu_ttvasf_MuTTVASys_uncorr_up, &b_mu_ttvasf_MuTTVASys_uncorr_up);
   fChain[ifile]->SetBranchAddress("mu_ttvasf_MuTTVASys_uncorr_down", &mu_ttvasf_MuTTVASys_uncorr_down, &b_mu_ttvasf_MuTTVASys_uncorr_down);
   fChain[ifile]->SetBranchAddress("mu_ttvasf_MuTTVASys_uncorr_BinNumber", &mu_ttvasf_MuTTVASys_uncorr_BinNumber, &b_mu_ttvasf_MuTTVASys_uncorr_BinNumber);
   fChain[ifile]->SetBranchAddress("mu_ttvasf_MuTTVASys_uncorr_MaxBinNumber", &mu_ttvasf_MuTTVASys_uncorr_MaxBinNumber, &b_mu_ttvasf_MuTTVASys_uncorr_MaxBinNumber);
   fChain[ifile]->SetBranchAddress("mu_ttvasf_MuTTVASys_corr_QCDTEMPLATE_down", &mu_ttvasf_MuTTVASys_corr_QCDTEMPLATE_down, &b_mu_ttvasf_MuTTVASys_corr_QCDTEMPLATE_down);
   fChain[ifile]->SetBranchAddress("mu_ttvasf_MuTTVASys_corr_LUMIUNCERT_down", &mu_ttvasf_MuTTVASys_corr_LUMIUNCERT_down, &b_mu_ttvasf_MuTTVASys_corr_LUMIUNCERT_down);
   fChain[ifile]->SetBranchAddress("mu_ttvasf_MuTTVASys_corr_BKGFRACTION_down", &mu_ttvasf_MuTTVASys_corr_BKGFRACTION_down, &b_mu_ttvasf_MuTTVASys_corr_BKGFRACTION_down);
   fChain[ifile]->SetBranchAddress("mu_ttvasf_MuTTVASys_corr_MCXSEC_down", &mu_ttvasf_MuTTVASys_corr_MCXSEC_down, &b_mu_ttvasf_MuTTVASys_corr_MCXSEC_down);
   fChain[ifile]->SetBranchAddress("mu_ttvasf_MuTTVASys_corr_SUPRESSIONSCALE_down", &mu_ttvasf_MuTTVASys_corr_SUPRESSIONSCALE_down, &b_mu_ttvasf_MuTTVASys_corr_SUPRESSIONSCALE_down);
   fChain[ifile]->SetBranchAddress("mu_ttvasf_MuTTVASys_corr_QCDTEMPLATE_up", &mu_ttvasf_MuTTVASys_corr_QCDTEMPLATE_up, &b_mu_ttvasf_MuTTVASys_corr_QCDTEMPLATE_up);
   fChain[ifile]->SetBranchAddress("mu_ttvasf_MuTTVASys_corr_LUMIUNCERT_up", &mu_ttvasf_MuTTVASys_corr_LUMIUNCERT_up, &b_mu_ttvasf_MuTTVASys_corr_LUMIUNCERT_up);
   fChain[ifile]->SetBranchAddress("mu_ttvasf_MuTTVASys_corr_BKGFRACTION_up", &mu_ttvasf_MuTTVASys_corr_BKGFRACTION_up, &b_mu_ttvasf_MuTTVASys_corr_BKGFRACTION_up);
   fChain[ifile]->SetBranchAddress("mu_ttvasf_MuTTVASys_corr_MCXSEC_up", &mu_ttvasf_MuTTVASys_corr_MCXSEC_up, &b_mu_ttvasf_MuTTVASys_corr_MCXSEC_up);
   fChain[ifile]->SetBranchAddress("mu_ttvasf_MuTTVASys_corr_SUPRESSIONSCALE_up", &mu_ttvasf_MuTTVASys_corr_SUPRESSIONSCALE_up, &b_mu_ttvasf_MuTTVASys_corr_SUPRESSIONSCALE_up);
   fChain[ifile]->SetBranchAddress("mu_trigsf_MuTrigSys_PtEta_up", &mu_trigsf_MuTrigSys_PtEta_up, &b_mu_trigsf_MuTrigSys_PtEta_up);
   fChain[ifile]->SetBranchAddress("mu_trigsf_MuTrigSys_PtEta_down", &mu_trigsf_MuTrigSys_PtEta_down, &b_mu_trigsf_MuTrigSys_PtEta_down);
   fChain[ifile]->SetBranchAddress("mu_trigsf_MuTrigSys_PtEta_uncorr_BinNumber", &mu_trigsf_MuTrigSys_PtEta_uncorr_BinNumber, &b_mu_trigsf_MuTrigSys_PtEta_uncorr_BinNumber);
   fChain[ifile]->SetBranchAddress("mu_trigsf_MuTrigSys_PtEta_uncorr_MaxBinNumber", &mu_trigsf_MuTrigSys_PtEta_uncorr_MaxBinNumber, &b_mu_trigsf_MuTrigSys_PtEta_uncorr_MaxBinNumber);
   fChain[ifile]->SetBranchAddress("mu_trigsf_MuTrigSys_PtEta_corr_iso_loose_avg", &mu_trigsf_MuTrigSys_PtEta_corr_iso_loose_avg, &b_mu_trigsf_MuTrigSys_PtEta_corr_iso_loose_avg);
   fChain[ifile]->SetBranchAddress("mu_trigsf_MuTrigSys_PtEta_corr_dPhi_avg", &mu_trigsf_MuTrigSys_PtEta_corr_dPhi_avg, &b_mu_trigsf_MuTrigSys_PtEta_corr_dPhi_avg);
   fChain[ifile]->SetBranchAddress("mu_trigsf_MuTrigSys_PtEta_corr_noIP_avg", &mu_trigsf_MuTrigSys_PtEta_corr_noIP_avg, &b_mu_trigsf_MuTrigSys_PtEta_corr_noIP_avg);
   fChain[ifile]->SetBranchAddress("mu_trigsf_MuTrigSys_PtEta_corr_iso_tight_avg", &mu_trigsf_MuTrigSys_PtEta_corr_iso_tight_avg, &b_mu_trigsf_MuTrigSys_PtEta_corr_iso_tight_avg);
   fChain[ifile]->SetBranchAddress("mu_trigsf_MuTrigSys_PtEta_corr_mlltight_avg", &mu_trigsf_MuTrigSys_PtEta_corr_mlltight_avg, &b_mu_trigsf_MuTrigSys_PtEta_corr_mlltight_avg);
   fChain[ifile]->SetBranchAddress("el_pt", &el_pt, &b_el_pt);
   fChain[ifile]->SetBranchAddress("el_eta", &el_eta, &b_el_eta);
   fChain[ifile]->SetBranchAddress("el_phi", &el_phi, &b_el_phi);
   fChain[ifile]->SetBranchAddress("el_qOverP", &el_qOverP, &b_el_qOverP);
   fChain[ifile]->SetBranchAddress("el_charge", &el_charge, &b_el_charge);
   fChain[ifile]->SetBranchAddress("el_d0sig", &el_d0sig, &b_el_d0sig);
   fChain[ifile]->SetBranchAddress("el_delta_z0", &el_delta_z0, &b_el_delta_z0);
   fChain[ifile]->SetBranchAddress("el_isTight", &el_isTight, &b_el_isTight);
   fChain[ifile]->SetBranchAddress("el_isMedium", &el_isMedium, &b_el_isMedium);
   fChain[ifile]->SetBranchAddress("el_trigMatch", &el_trigMatch, &b_el_trigMatch);
   fChain[ifile]->SetBranchAddress("el_inrecoil", &el_inrecoil, &b_el_inrecoil);
   fChain[ifile]->SetBranchAddress("el_inrecoil_loose", &el_inrecoil_loose, &b_el_inrecoil_loose);
   fChain[ifile]->SetBranchAddress("el_inrecoil_medium", &el_inrecoil_medium, &b_el_inrecoil_medium);
   fChain[ifile]->SetBranchAddress("el_isolation_ptcone20", &el_isolation_ptcone20, &b_el_isolation_ptcone20);
   fChain[ifile]->SetBranchAddress("el_isolation_ptvarcone20", &el_isolation_ptvarcone20, &b_el_isolation_ptvarcone20);
   fChain[ifile]->SetBranchAddress("el_isolation_ptvarcone30", &el_isolation_ptvarcone30, &b_el_isolation_ptvarcone30);
   fChain[ifile]->SetBranchAddress("el_isolation_ptvarcone40", &el_isolation_ptvarcone40, &b_el_isolation_ptvarcone40);
   fChain[ifile]->SetBranchAddress("el_isolation_topoetcone20", &el_isolation_topoetcone20, &b_el_isolation_topoetcone20);
   fChain[ifile]->SetBranchAddress("el_isolation_topoetcone20ptCorrection", &el_isolation_topoetcone20ptCorrection, &b_el_isolation_topoetcone20ptCorrection);
   fChain[ifile]->SetBranchAddress("el_isolation_topoetcone30", &el_isolation_topoetcone30, &b_el_isolation_topoetcone30);
   fChain[ifile]->SetBranchAddress("el_isolation_topoetcone30ptCorrection", &el_isolation_topoetcone30ptCorrection, &b_el_isolation_topoetcone30ptCorrection);
   fChain[ifile]->SetBranchAddress("el_isolation_topoetcone40", &el_isolation_topoetcone40, &b_el_isolation_topoetcone40);
   fChain[ifile]->SetBranchAddress("el_isolation_topoetcone40ptCorrection", &el_isolation_topoetcone40ptCorrection, &b_el_isolation_topoetcone40ptCorrection);
   fChain[ifile]->SetBranchAddress("el_isIsolated", &el_isIsolated, &b_el_isIsolated);
   fChain[ifile]->SetBranchAddress("el_corrected_pt", &el_corrected_pt, &b_el_corrected_pt);
   fChain[ifile]->SetBranchAddress("el_recosf", &el_recosf, &b_el_recosf);
   fChain[ifile]->SetBranchAddress("el_recomceff", &el_recomceff, &b_el_recomceff);
   fChain[ifile]->SetBranchAddress("el_isosf", &el_isosf, &b_el_isosf);
   fChain[ifile]->SetBranchAddress("el_isomceff", &el_isomceff, &b_el_isomceff);
   fChain[ifile]->SetBranchAddress("el_idsf", &el_idsf, &b_el_idsf);
   fChain[ifile]->SetBranchAddress("el_idmceff", &el_idmceff, &b_el_idmceff);
   fChain[ifile]->SetBranchAddress("el_trigsf", &el_trigsf, &b_el_trigsf);
   fChain[ifile]->SetBranchAddress("el_trigmceff", &el_trigmceff, &b_el_trigmceff);
   fChain[ifile]->SetBranchAddress("el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP0__1down", &el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP0__1down, &b_el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP0__1down);
   fChain[ifile]->SetBranchAddress("el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP0__1up", &el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP0__1up, &b_el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP0__1up);
   fChain[ifile]->SetBranchAddress("el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP1__1down", &el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP1__1down, &b_el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP1__1down);
   fChain[ifile]->SetBranchAddress("el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP1__1up", &el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP1__1up, &b_el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP1__1up);
   fChain[ifile]->SetBranchAddress("el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP2__1down", &el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP2__1down, &b_el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP2__1down);
   fChain[ifile]->SetBranchAddress("el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP2__1up", &el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP2__1up, &b_el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP2__1up);
   fChain[ifile]->SetBranchAddress("el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP3__1down", &el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP3__1down, &b_el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP3__1down);
   fChain[ifile]->SetBranchAddress("el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP3__1up", &el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP3__1up, &b_el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP3__1up);
   fChain[ifile]->SetBranchAddress("el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP4__1down", &el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP4__1down, &b_el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP4__1down);
   fChain[ifile]->SetBranchAddress("el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP4__1up", &el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP4__1up, &b_el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP4__1up);
   fChain[ifile]->SetBranchAddress("el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP5__1down", &el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP5__1down, &b_el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP5__1down);
   fChain[ifile]->SetBranchAddress("el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP5__1up", &el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP5__1up, &b_el_sysrecosf_EL_EFF_Reco_CorrUncertaintyNP5__1up);
   fChain[ifile]->SetBranchAddress("el_sysrecosf_EL_EFF_Reco_FULL_UncorrUncertaintyNP33__1down", &el_sysrecosf_EL_EFF_Reco_FULL_UncorrUncertaintyNP33__1down, &b_el_sysrecosf_EL_EFF_Reco_FULL_UncorrUncertaintyNP33__1down);
   fChain[ifile]->SetBranchAddress("el_sysrecosf_EL_EFF_Reco_FULL_UncorrUncertaintyNP33__1up", &el_sysrecosf_EL_EFF_Reco_FULL_UncorrUncertaintyNP33__1up, &b_el_sysrecosf_EL_EFF_Reco_FULL_UncorrUncertaintyNP33__1up);
   fChain[ifile]->SetBranchAddress("el_isosf_ElIsoSys_FullSim_FixedCutLoose_corr11_up", &el_isosf_ElIsoSys_FullSim_FixedCutLoose_corr11_up, &b_el_isosf_ElIsoSys_FullSim_FixedCutLoose_corr11_up);
   fChain[ifile]->SetBranchAddress("el_isosf_ElIsoSys_FullSim_FixedCutLoose_corr11_down", &el_isosf_ElIsoSys_FullSim_FixedCutLoose_corr11_down, &b_el_isosf_ElIsoSys_FullSim_FixedCutLoose_corr11_down);
   fChain[ifile]->SetBranchAddress("el_isosf_ElIsoSys_FullSim_FixedCutLoose_corr12_up", &el_isosf_ElIsoSys_FullSim_FixedCutLoose_corr12_up, &b_el_isosf_ElIsoSys_FullSim_FixedCutLoose_corr12_up);
   fChain[ifile]->SetBranchAddress("el_isosf_ElIsoSys_FullSim_FixedCutLoose_corr12_down", &el_isosf_ElIsoSys_FullSim_FixedCutLoose_corr12_down, &b_el_isosf_ElIsoSys_FullSim_FixedCutLoose_corr12_down);
   fChain[ifile]->SetBranchAddress("el_isosf_ElIsoSys_FullSim_FixedCutLoose_corr13_up", &el_isosf_ElIsoSys_FullSim_FixedCutLoose_corr13_up, &b_el_isosf_ElIsoSys_FullSim_FixedCutLoose_corr13_up);
   fChain[ifile]->SetBranchAddress("el_isosf_ElIsoSys_FullSim_FixedCutLoose_corr13_down", &el_isosf_ElIsoSys_FullSim_FixedCutLoose_corr13_down, &b_el_isosf_ElIsoSys_FullSim_FixedCutLoose_corr13_down);
   fChain[ifile]->SetBranchAddress("el_isosf_ElIsoSys_FullSim_FixedCutLoose_corr14_up", &el_isosf_ElIsoSys_FullSim_FixedCutLoose_corr14_up, &b_el_isosf_ElIsoSys_FullSim_FixedCutLoose_corr14_up);
   fChain[ifile]->SetBranchAddress("el_isosf_ElIsoSys_FullSim_FixedCutLoose_corr14_down", &el_isosf_ElIsoSys_FullSim_FixedCutLoose_corr14_down, &b_el_isosf_ElIsoSys_FullSim_FixedCutLoose_corr14_down);
   fChain[ifile]->SetBranchAddress("el_isosf_ElIsoSys_uncorr_up", &el_isosf_ElIsoSys_uncorr_up, &b_el_isosf_ElIsoSys_uncorr_up);
   fChain[ifile]->SetBranchAddress("el_isosf_ElIsoSys_uncorr_down", &el_isosf_ElIsoSys_uncorr_down, &b_el_isosf_ElIsoSys_uncorr_down);
   fChain[ifile]->SetBranchAddress("el_isosf_ElIsoSys_uncorr_BinNumber", &el_isosf_ElIsoSys_uncorr_BinNumber, &b_el_isosf_ElIsoSys_uncorr_BinNumber);
   fChain[ifile]->SetBranchAddress("el_isosf_ElIsoSys_uncorr_MaxBinNumber", &el_isosf_ElIsoSys_uncorr_MaxBinNumber, &b_el_isosf_ElIsoSys_uncorr_MaxBinNumber);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr1_up", &el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr1_up, &b_el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr1_up);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr1_down", &el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr1_down, &b_el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr1_down);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr10_up", &el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr10_up, &b_el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr10_up);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr10_down", &el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr10_down, &b_el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr10_down);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr11_up", &el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr11_up, &b_el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr11_up);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr11_down", &el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr11_down, &b_el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr11_down);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr12_up", &el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr12_up, &b_el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr12_up);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr12_down", &el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr12_down, &b_el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr12_down);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr13_up", &el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr13_up, &b_el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr13_up);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr13_down", &el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr13_down, &b_el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr13_down);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr14_up", &el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr14_up, &b_el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr14_up);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr14_down", &el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr14_down, &b_el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr14_down);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr2_up", &el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr2_up, &b_el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr2_up);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr2_down", &el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr2_down, &b_el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr2_down);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr3_up", &el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr3_up, &b_el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr3_up);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr3_down", &el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr3_down, &b_el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr3_down);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr4_up", &el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr4_up, &b_el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr4_up);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr4_down", &el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr4_down, &b_el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr4_down);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr5_up", &el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr5_up, &b_el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr5_up);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr5_down", &el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr5_down, &b_el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr5_down);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr6_up", &el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr6_up, &b_el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr6_up);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr6_down", &el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr6_down, &b_el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr6_down);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr7_up", &el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr7_up, &b_el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr7_up);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr7_down", &el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr7_down, &b_el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr7_down);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr8_up", &el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr8_up, &b_el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr8_up);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr8_down", &el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr8_down, &b_el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr8_down);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr9_up", &el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr9_up, &b_el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr9_up);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr9_down", &el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr9_down, &b_el_idsf_ElIDSys_FullSim_MediumLLH_d0z0_corr9_down);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_uncorr_up", &el_idsf_ElIDSys_uncorr_up, &b_el_idsf_ElIDSys_uncorr_up);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_uncorr_down", &el_idsf_ElIDSys_uncorr_down, &b_el_idsf_ElIDSys_uncorr_down);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_uncorr_BinNumber", &el_idsf_ElIDSys_uncorr_BinNumber, &b_el_idsf_ElIDSys_uncorr_BinNumber);
   fChain[ifile]->SetBranchAddress("el_idsf_ElIDSys_uncorr_MaxBinNumber", &el_idsf_ElIDSys_uncorr_MaxBinNumber, &b_el_idsf_ElIDSys_uncorr_MaxBinNumber);
   fChain[ifile]->SetBranchAddress("el_trigsf_ElTrigSys_FullSim_corr10_up", &el_trigsf_ElTrigSys_FullSim_corr10_up, &b_el_trigsf_ElTrigSys_FullSim_corr10_up);
   fChain[ifile]->SetBranchAddress("el_trigsf_ElTrigSys_FullSim_corr10_down", &el_trigsf_ElTrigSys_FullSim_corr10_down, &b_el_trigsf_ElTrigSys_FullSim_corr10_down);
   fChain[ifile]->SetBranchAddress("el_trigsf_ElTrigSys_FullSim_corr11_up", &el_trigsf_ElTrigSys_FullSim_corr11_up, &b_el_trigsf_ElTrigSys_FullSim_corr11_up);
   fChain[ifile]->SetBranchAddress("el_trigsf_ElTrigSys_FullSim_corr11_down", &el_trigsf_ElTrigSys_FullSim_corr11_down, &b_el_trigsf_ElTrigSys_FullSim_corr11_down);
   fChain[ifile]->SetBranchAddress("el_trigsf_ElTrigSys_FullSim_corr12_up", &el_trigsf_ElTrigSys_FullSim_corr12_up, &b_el_trigsf_ElTrigSys_FullSim_corr12_up);
   fChain[ifile]->SetBranchAddress("el_trigsf_ElTrigSys_FullSim_corr12_down", &el_trigsf_ElTrigSys_FullSim_corr12_down, &b_el_trigsf_ElTrigSys_FullSim_corr12_down);
   fChain[ifile]->SetBranchAddress("el_trigsf_ElTrigSys_FullSim_corr13_up", &el_trigsf_ElTrigSys_FullSim_corr13_up, &b_el_trigsf_ElTrigSys_FullSim_corr13_up);
   fChain[ifile]->SetBranchAddress("el_trigsf_ElTrigSys_FullSim_corr13_down", &el_trigsf_ElTrigSys_FullSim_corr13_down, &b_el_trigsf_ElTrigSys_FullSim_corr13_down);
   fChain[ifile]->SetBranchAddress("el_trigsf_ElTrigSys_FullSim_corr14_up", &el_trigsf_ElTrigSys_FullSim_corr14_up, &b_el_trigsf_ElTrigSys_FullSim_corr14_up);
   fChain[ifile]->SetBranchAddress("el_trigsf_ElTrigSys_FullSim_corr14_down", &el_trigsf_ElTrigSys_FullSim_corr14_down, &b_el_trigsf_ElTrigSys_FullSim_corr14_down);
   fChain[ifile]->SetBranchAddress("el_trigsf_ElTrigSys_FullSim_corr8_up", &el_trigsf_ElTrigSys_FullSim_corr8_up, &b_el_trigsf_ElTrigSys_FullSim_corr8_up);
   fChain[ifile]->SetBranchAddress("el_trigsf_ElTrigSys_FullSim_corr8_down", &el_trigsf_ElTrigSys_FullSim_corr8_down, &b_el_trigsf_ElTrigSys_FullSim_corr8_down);
   fChain[ifile]->SetBranchAddress("el_trigsf_ElTrigSys_FullSim_corr9_up", &el_trigsf_ElTrigSys_FullSim_corr9_up, &b_el_trigsf_ElTrigSys_FullSim_corr9_up);
   fChain[ifile]->SetBranchAddress("el_trigsf_ElTrigSys_FullSim_corr9_down", &el_trigsf_ElTrigSys_FullSim_corr9_down, &b_el_trigsf_ElTrigSys_FullSim_corr9_down);
   fChain[ifile]->SetBranchAddress("el_trigsf_ElTrigSys_uncorr_up", &el_trigsf_ElTrigSys_uncorr_up, &b_el_trigsf_ElTrigSys_uncorr_up);
   fChain[ifile]->SetBranchAddress("el_trigsf_ElTrigSys_uncorr_down", &el_trigsf_ElTrigSys_uncorr_down, &b_el_trigsf_ElTrigSys_uncorr_down);
   fChain[ifile]->SetBranchAddress("el_trigsf_ElTrigSys_uncorr_BinNumber", &el_trigsf_ElTrigSys_uncorr_BinNumber, &b_el_trigsf_ElTrigSys_uncorr_BinNumber);
   fChain[ifile]->SetBranchAddress("el_trigsf_ElTrigSys_uncorr_MaxBinNumber", &el_trigsf_ElTrigSys_uncorr_MaxBinNumber, &b_el_trigsf_ElTrigSys_uncorr_MaxBinNumber);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleUp_NP1", &el_corrected_pt_scaleUp_NP1, &b_el_corrected_pt_scaleUp_NP1);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleUp_NP2", &el_corrected_pt_scaleUp_NP2, &b_el_corrected_pt_scaleUp_NP2);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleUp_NP3", &el_corrected_pt_scaleUp_NP3, &b_el_corrected_pt_scaleUp_NP3);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleUp_NP4", &el_corrected_pt_scaleUp_NP4, &b_el_corrected_pt_scaleUp_NP4);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleUp_NP5", &el_corrected_pt_scaleUp_NP5, &b_el_corrected_pt_scaleUp_NP5);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleUp_NP6", &el_corrected_pt_scaleUp_NP6, &b_el_corrected_pt_scaleUp_NP6);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleUp_NP7", &el_corrected_pt_scaleUp_NP7, &b_el_corrected_pt_scaleUp_NP7);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleUp_NP8", &el_corrected_pt_scaleUp_NP8, &b_el_corrected_pt_scaleUp_NP8);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleUp_NP9", &el_corrected_pt_scaleUp_NP9, &b_el_corrected_pt_scaleUp_NP9);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleUp_NP10", &el_corrected_pt_scaleUp_NP10, &b_el_corrected_pt_scaleUp_NP10);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleUp_NP11", &el_corrected_pt_scaleUp_NP11, &b_el_corrected_pt_scaleUp_NP11);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleUp_NP12", &el_corrected_pt_scaleUp_NP12, &b_el_corrected_pt_scaleUp_NP12);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleUp_NP13", &el_corrected_pt_scaleUp_NP13, &b_el_corrected_pt_scaleUp_NP13);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleUp_NP14", &el_corrected_pt_scaleUp_NP14, &b_el_corrected_pt_scaleUp_NP14);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleUp_NP15", &el_corrected_pt_scaleUp_NP15, &b_el_corrected_pt_scaleUp_NP15);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleUp_NP16", &el_corrected_pt_scaleUp_NP16, &b_el_corrected_pt_scaleUp_NP16);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleUp_NP17", &el_corrected_pt_scaleUp_NP17, &b_el_corrected_pt_scaleUp_NP17);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleUp_NP18", &el_corrected_pt_scaleUp_NP18, &b_el_corrected_pt_scaleUp_NP18);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleUp_NP19", &el_corrected_pt_scaleUp_NP19, &b_el_corrected_pt_scaleUp_NP19);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleUp_NP20", &el_corrected_pt_scaleUp_NP20, &b_el_corrected_pt_scaleUp_NP20);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleUp_NP21", &el_corrected_pt_scaleUp_NP21, &b_el_corrected_pt_scaleUp_NP21);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleUp_NP22", &el_corrected_pt_scaleUp_NP22, &b_el_corrected_pt_scaleUp_NP22);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleUp_NP23", &el_corrected_pt_scaleUp_NP23, &b_el_corrected_pt_scaleUp_NP23);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleUp_NP24", &el_corrected_pt_scaleUp_NP24, &b_el_corrected_pt_scaleUp_NP24);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleDown_NP1", &el_corrected_pt_scaleDown_NP1, &b_el_corrected_pt_scaleDown_NP1);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleDown_NP2", &el_corrected_pt_scaleDown_NP2, &b_el_corrected_pt_scaleDown_NP2);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleDown_NP3", &el_corrected_pt_scaleDown_NP3, &b_el_corrected_pt_scaleDown_NP3);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleDown_NP4", &el_corrected_pt_scaleDown_NP4, &b_el_corrected_pt_scaleDown_NP4);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleDown_NP5", &el_corrected_pt_scaleDown_NP5, &b_el_corrected_pt_scaleDown_NP5);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleDown_NP6", &el_corrected_pt_scaleDown_NP6, &b_el_corrected_pt_scaleDown_NP6);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleDown_NP7", &el_corrected_pt_scaleDown_NP7, &b_el_corrected_pt_scaleDown_NP7);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleDown_NP8", &el_corrected_pt_scaleDown_NP8, &b_el_corrected_pt_scaleDown_NP8);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleDown_NP9", &el_corrected_pt_scaleDown_NP9, &b_el_corrected_pt_scaleDown_NP9);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleDown_NP10", &el_corrected_pt_scaleDown_NP10, &b_el_corrected_pt_scaleDown_NP10);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleDown_NP11", &el_corrected_pt_scaleDown_NP11, &b_el_corrected_pt_scaleDown_NP11);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleDown_NP12", &el_corrected_pt_scaleDown_NP12, &b_el_corrected_pt_scaleDown_NP12);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleDown_NP13", &el_corrected_pt_scaleDown_NP13, &b_el_corrected_pt_scaleDown_NP13);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleDown_NP14", &el_corrected_pt_scaleDown_NP14, &b_el_corrected_pt_scaleDown_NP14);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleDown_NP15", &el_corrected_pt_scaleDown_NP15, &b_el_corrected_pt_scaleDown_NP15);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleDown_NP16", &el_corrected_pt_scaleDown_NP16, &b_el_corrected_pt_scaleDown_NP16);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleDown_NP17", &el_corrected_pt_scaleDown_NP17, &b_el_corrected_pt_scaleDown_NP17);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleDown_NP18", &el_corrected_pt_scaleDown_NP18, &b_el_corrected_pt_scaleDown_NP18);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleDown_NP19", &el_corrected_pt_scaleDown_NP19, &b_el_corrected_pt_scaleDown_NP19);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleDown_NP20", &el_corrected_pt_scaleDown_NP20, &b_el_corrected_pt_scaleDown_NP20);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleDown_NP21", &el_corrected_pt_scaleDown_NP21, &b_el_corrected_pt_scaleDown_NP21);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleDown_NP22", &el_corrected_pt_scaleDown_NP22, &b_el_corrected_pt_scaleDown_NP22);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleDown_NP23", &el_corrected_pt_scaleDown_NP23, &b_el_corrected_pt_scaleDown_NP23);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_scaleDown_NP24", &el_corrected_pt_scaleDown_NP24, &b_el_corrected_pt_scaleDown_NP24);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cUp_NP1", &el_corrected_pt_cUp_NP1, &b_el_corrected_pt_cUp_NP1);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cUp_NP2", &el_corrected_pt_cUp_NP2, &b_el_corrected_pt_cUp_NP2);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cUp_NP3", &el_corrected_pt_cUp_NP3, &b_el_corrected_pt_cUp_NP3);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cUp_NP4", &el_corrected_pt_cUp_NP4, &b_el_corrected_pt_cUp_NP4);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cUp_NP5", &el_corrected_pt_cUp_NP5, &b_el_corrected_pt_cUp_NP5);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cUp_NP6", &el_corrected_pt_cUp_NP6, &b_el_corrected_pt_cUp_NP6);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cUp_NP7", &el_corrected_pt_cUp_NP7, &b_el_corrected_pt_cUp_NP7);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cUp_NP8", &el_corrected_pt_cUp_NP8, &b_el_corrected_pt_cUp_NP8);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cUp_NP9", &el_corrected_pt_cUp_NP9, &b_el_corrected_pt_cUp_NP9);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cUp_NP10", &el_corrected_pt_cUp_NP10, &b_el_corrected_pt_cUp_NP10);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cUp_NP11", &el_corrected_pt_cUp_NP11, &b_el_corrected_pt_cUp_NP11);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cUp_NP12", &el_corrected_pt_cUp_NP12, &b_el_corrected_pt_cUp_NP12);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cUp_NP13", &el_corrected_pt_cUp_NP13, &b_el_corrected_pt_cUp_NP13);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cUp_NP14", &el_corrected_pt_cUp_NP14, &b_el_corrected_pt_cUp_NP14);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cUp_NP15", &el_corrected_pt_cUp_NP15, &b_el_corrected_pt_cUp_NP15);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cUp_NP16", &el_corrected_pt_cUp_NP16, &b_el_corrected_pt_cUp_NP16);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cUp_NP17", &el_corrected_pt_cUp_NP17, &b_el_corrected_pt_cUp_NP17);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cUp_NP18", &el_corrected_pt_cUp_NP18, &b_el_corrected_pt_cUp_NP18);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cUp_NP19", &el_corrected_pt_cUp_NP19, &b_el_corrected_pt_cUp_NP19);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cUp_NP20", &el_corrected_pt_cUp_NP20, &b_el_corrected_pt_cUp_NP20);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cUp_NP21", &el_corrected_pt_cUp_NP21, &b_el_corrected_pt_cUp_NP21);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cUp_NP22", &el_corrected_pt_cUp_NP22, &b_el_corrected_pt_cUp_NP22);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cUp_NP23", &el_corrected_pt_cUp_NP23, &b_el_corrected_pt_cUp_NP23);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cUp_NP24", &el_corrected_pt_cUp_NP24, &b_el_corrected_pt_cUp_NP24);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cDown_NP1", &el_corrected_pt_cDown_NP1, &b_el_corrected_pt_cDown_NP1);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cDown_NP2", &el_corrected_pt_cDown_NP2, &b_el_corrected_pt_cDown_NP2);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cDown_NP3", &el_corrected_pt_cDown_NP3, &b_el_corrected_pt_cDown_NP3);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cDown_NP4", &el_corrected_pt_cDown_NP4, &b_el_corrected_pt_cDown_NP4);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cDown_NP5", &el_corrected_pt_cDown_NP5, &b_el_corrected_pt_cDown_NP5);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cDown_NP6", &el_corrected_pt_cDown_NP6, &b_el_corrected_pt_cDown_NP6);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cDown_NP7", &el_corrected_pt_cDown_NP7, &b_el_corrected_pt_cDown_NP7);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cDown_NP8", &el_corrected_pt_cDown_NP8, &b_el_corrected_pt_cDown_NP8);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cDown_NP9", &el_corrected_pt_cDown_NP9, &b_el_corrected_pt_cDown_NP9);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cDown_NP10", &el_corrected_pt_cDown_NP10, &b_el_corrected_pt_cDown_NP10);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cDown_NP11", &el_corrected_pt_cDown_NP11, &b_el_corrected_pt_cDown_NP11);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cDown_NP12", &el_corrected_pt_cDown_NP12, &b_el_corrected_pt_cDown_NP12);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cDown_NP13", &el_corrected_pt_cDown_NP13, &b_el_corrected_pt_cDown_NP13);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cDown_NP14", &el_corrected_pt_cDown_NP14, &b_el_corrected_pt_cDown_NP14);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cDown_NP15", &el_corrected_pt_cDown_NP15, &b_el_corrected_pt_cDown_NP15);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cDown_NP16", &el_corrected_pt_cDown_NP16, &b_el_corrected_pt_cDown_NP16);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cDown_NP17", &el_corrected_pt_cDown_NP17, &b_el_corrected_pt_cDown_NP17);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cDown_NP18", &el_corrected_pt_cDown_NP18, &b_el_corrected_pt_cDown_NP18);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cDown_NP19", &el_corrected_pt_cDown_NP19, &b_el_corrected_pt_cDown_NP19);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cDown_NP20", &el_corrected_pt_cDown_NP20, &b_el_corrected_pt_cDown_NP20);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cDown_NP21", &el_corrected_pt_cDown_NP21, &b_el_corrected_pt_cDown_NP21);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cDown_NP22", &el_corrected_pt_cDown_NP22, &b_el_corrected_pt_cDown_NP22);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cDown_NP23", &el_corrected_pt_cDown_NP23, &b_el_corrected_pt_cDown_NP23);
   fChain[ifile]->SetBranchAddress("el_corrected_pt_cDown_NP24", &el_corrected_pt_cDown_NP24, &b_el_corrected_pt_cDown_NP24);
   fChain[ifile]->SetBranchAddress("fwdel_pt", &fwdel_pt, &b_fwdel_pt);
   fChain[ifile]->SetBranchAddress("fwdel_eta", &fwdel_eta, &b_fwdel_eta);
   fChain[ifile]->SetBranchAddress("fwdel_phi", &fwdel_phi, &b_fwdel_phi);
   fChain[ifile]->SetBranchAddress("u_pt_el_loose_pfo", &u_pt_el_loose_pfo, &b_u_pt_el_loose_pfo);
   fChain[ifile]->SetBranchAddress("u_pt_el_loose_pfoCharged", &u_pt_el_loose_pfoCharged, &b_u_pt_el_loose_pfoCharged);
   fChain[ifile]->SetBranchAddress("u_pt_el_loose_pfoEM", &u_pt_el_loose_pfoEM, &b_u_pt_el_loose_pfoEM);
   fChain[ifile]->SetBranchAddress("u_pt_el_loose_pfoEMCentral", &u_pt_el_loose_pfoEMCentral, &b_u_pt_el_loose_pfoEMCentral);
   fChain[ifile]->SetBranchAddress("u_pt_el_loose_pfoEMForward", &u_pt_el_loose_pfoEMForward, &b_u_pt_el_loose_pfoEMForward);
   fChain[ifile]->SetBranchAddress("u_pt_el_loose_pfoNeutral", &u_pt_el_loose_pfoNeutral, &b_u_pt_el_loose_pfoNeutral);
   fChain[ifile]->SetBranchAddress("u_pt_el_loose_pfoNeutralEM", &u_pt_el_loose_pfoNeutralEM, &b_u_pt_el_loose_pfoNeutralEM);
   fChain[ifile]->SetBranchAddress("u_pt_el_loose_pfoNeutralEMCentral", &u_pt_el_loose_pfoNeutralEMCentral, &b_u_pt_el_loose_pfoNeutralEMCentral);
   fChain[ifile]->SetBranchAddress("u_pt_el_loose_pfoNeutralEMForward", &u_pt_el_loose_pfoNeutralEMForward, &b_u_pt_el_loose_pfoNeutralEMForward);
   fChain[ifile]->SetBranchAddress("u_pt_el_loose_pfovor", &u_pt_el_loose_pfovor, &b_u_pt_el_loose_pfovor);
   fChain[ifile]->SetBranchAddress("u_pt_el_loose_pfovorsp", &u_pt_el_loose_pfovorsp, &b_u_pt_el_loose_pfovorsp);
   fChain[ifile]->SetBranchAddress("u_pt_el_medium_pfo", &u_pt_el_medium_pfo, &b_u_pt_el_medium_pfo);
   fChain[ifile]->SetBranchAddress("u_pt_el_medium_pfoCharged", &u_pt_el_medium_pfoCharged, &b_u_pt_el_medium_pfoCharged);
   fChain[ifile]->SetBranchAddress("u_pt_el_medium_pfoEM", &u_pt_el_medium_pfoEM, &b_u_pt_el_medium_pfoEM);
   fChain[ifile]->SetBranchAddress("u_pt_el_medium_pfoEMCentral", &u_pt_el_medium_pfoEMCentral, &b_u_pt_el_medium_pfoEMCentral);
   fChain[ifile]->SetBranchAddress("u_pt_el_medium_pfoEMForward", &u_pt_el_medium_pfoEMForward, &b_u_pt_el_medium_pfoEMForward);
   fChain[ifile]->SetBranchAddress("u_pt_el_medium_pfoNeutral", &u_pt_el_medium_pfoNeutral, &b_u_pt_el_medium_pfoNeutral);
   fChain[ifile]->SetBranchAddress("u_pt_el_medium_pfoNeutralEM", &u_pt_el_medium_pfoNeutralEM, &b_u_pt_el_medium_pfoNeutralEM);
   fChain[ifile]->SetBranchAddress("u_pt_el_medium_pfoNeutralEMCentral", &u_pt_el_medium_pfoNeutralEMCentral, &b_u_pt_el_medium_pfoNeutralEMCentral);
   fChain[ifile]->SetBranchAddress("u_pt_el_medium_pfoNeutralEMForward", &u_pt_el_medium_pfoNeutralEMForward, &b_u_pt_el_medium_pfoNeutralEMForward);
   fChain[ifile]->SetBranchAddress("u_pt_el_medium_pfovor", &u_pt_el_medium_pfovor, &b_u_pt_el_medium_pfovor);
   fChain[ifile]->SetBranchAddress("u_pt_el_medium_pfovorsp", &u_pt_el_medium_pfovorsp, &b_u_pt_el_medium_pfovorsp);
   fChain[ifile]->SetBranchAddress("u_phi_el_loose_pfo", &u_phi_el_loose_pfo, &b_u_phi_el_loose_pfo);
   fChain[ifile]->SetBranchAddress("u_phi_el_loose_pfoCharged", &u_phi_el_loose_pfoCharged, &b_u_phi_el_loose_pfoCharged);
   fChain[ifile]->SetBranchAddress("u_phi_el_loose_pfoEM", &u_phi_el_loose_pfoEM, &b_u_phi_el_loose_pfoEM);
   fChain[ifile]->SetBranchAddress("u_phi_el_loose_pfoEMCentral", &u_phi_el_loose_pfoEMCentral, &b_u_phi_el_loose_pfoEMCentral);
   fChain[ifile]->SetBranchAddress("u_phi_el_loose_pfoEMForwar ", &u_phi_el_loose_pfoEMForwar , &b_u_phi_el_loose_pfoEMForwar );
   fChain[ifile]->SetBranchAddress("u_phi_el_loose_pfoNeutral", &u_phi_el_loose_pfoNeutral, &b_u_phi_el_loose_pfoNeutral);
   fChain[ifile]->SetBranchAddress("u_phi_el_loose_pfoNeutralEM", &u_phi_el_loose_pfoNeutralEM, &b_u_phi_el_loose_pfoNeutralEM);
   fChain[ifile]->SetBranchAddress("u_phi_el_loose_pfoNeutralEMCentral", &u_phi_el_loose_pfoNeutralEMCentral, &b_u_phi_el_loose_pfoNeutralEMCentral);
   fChain[ifile]->SetBranchAddress("u_phi_el_loose_pfoNeutralEMForwar ", &u_phi_el_loose_pfoNeutralEMForwar , &b_u_phi_el_loose_pfoNeutralEMForwar );
   fChain[ifile]->SetBranchAddress("u_phi_el_loose_pfovor", &u_phi_el_loose_pfovor, &b_u_phi_el_loose_pfovor);
   fChain[ifile]->SetBranchAddress("u_phi_el_loose_pfovorsp", &u_phi_el_loose_pfovorsp, &b_u_phi_el_loose_pfovorsp);
   fChain[ifile]->SetBranchAddress("u_phi_el_medium_pfo", &u_phi_el_medium_pfo, &b_u_phi_el_medium_pfo);
   fChain[ifile]->SetBranchAddress("u_phi_el_medium_pfoCharged", &u_phi_el_medium_pfoCharged, &b_u_phi_el_medium_pfoCharged);
   fChain[ifile]->SetBranchAddress("u_phi_el_medium_pfoEM", &u_phi_el_medium_pfoEM, &b_u_phi_el_medium_pfoEM);
   fChain[ifile]->SetBranchAddress("u_phi_el_medium_pfoEMCentral", &u_phi_el_medium_pfoEMCentral, &b_u_phi_el_medium_pfoEMCentral);
   fChain[ifile]->SetBranchAddress("u_phi_el_medium_pfoEMForward", &u_phi_el_medium_pfoEMForward, &b_u_phi_el_medium_pfoEMForward);
   fChain[ifile]->SetBranchAddress("u_phi_el_medium_pfoNeutral", &u_phi_el_medium_pfoNeutral, &b_u_phi_el_medium_pfoNeutral);
   fChain[ifile]->SetBranchAddress("u_phi_el_medium_pfoNeutralEM", &u_phi_el_medium_pfoNeutralEM, &b_u_phi_el_medium_pfoNeutralEM);
   fChain[ifile]->SetBranchAddress("u_phi_el_medium_pfoNeutralEMCentral", &u_phi_el_medium_pfoNeutralEMCentral, &b_u_phi_el_medium_pfoNeutralEMCentral);
   fChain[ifile]->SetBranchAddress("u_phi_el_medium_pfoNeutralEMForward", &u_phi_el_medium_pfoNeutralEMForward, &b_u_phi_el_medium_pfoNeutralEMForward);
   fChain[ifile]->SetBranchAddress("u_phi_el_medium_pfovor", &u_phi_el_medium_pfovor, &b_u_phi_el_medium_pfovor);
   fChain[ifile]->SetBranchAddress("u_phi_el_medium_pfovorsp", &u_phi_el_medium_pfovorsp, &b_u_phi_el_medium_pfovorsp);
   fChain[ifile]->SetBranchAddress("u_sumet_el_loose_pfo", &u_sumet_el_loose_pfo, &b_u_sumet_el_loose_pfo);
   fChain[ifile]->SetBranchAddress("u_sumet_el_loose_pfoCharged", &u_sumet_el_loose_pfoCharged, &b_u_sumet_el_loose_pfoCharged);
   fChain[ifile]->SetBranchAddress("u_sumet_el_loose_pfoEM", &u_sumet_el_loose_pfoEM, &b_u_sumet_el_loose_pfoEM);
   fChain[ifile]->SetBranchAddress("u_sumet_el_loose_pfoEMCentral", &u_sumet_el_loose_pfoEMCentral, &b_u_sumet_el_loose_pfoEMCentral);
   fChain[ifile]->SetBranchAddress("u_sumet_el_loose_pfoEMForward", &u_sumet_el_loose_pfoEMForward, &b_u_sumet_el_loose_pfoEMForward);
   fChain[ifile]->SetBranchAddress("u_sumet_el_loose_pfoNeutral", &u_sumet_el_loose_pfoNeutral, &b_u_sumet_el_loose_pfoNeutral);
   fChain[ifile]->SetBranchAddress("u_sumet_el_loose_pfoNeutralEM", &u_sumet_el_loose_pfoNeutralEM, &b_u_sumet_el_loose_pfoNeutralEM);
   fChain[ifile]->SetBranchAddress("u_sumet_el_loose_pfoNeutralEMCentral", &u_sumet_el_loose_pfoNeutralEMCentral, &b_u_sumet_el_loose_pfoNeutralEMCentral);
   fChain[ifile]->SetBranchAddress("u_sumet_el_loose_pfoNeutralEMForward", &u_sumet_el_loose_pfoNeutralEMForward, &b_u_sumet_el_loose_pfoNeutralEMForward);
   fChain[ifile]->SetBranchAddress("u_sumet_el_medium_pfo", &u_sumet_el_medium_pfo, &b_u_sumet_el_medium_pfo);
   fChain[ifile]->SetBranchAddress("u_sumet_el_medium_pfoCharged", &u_sumet_el_medium_pfoCharged, &b_u_sumet_el_medium_pfoCharged);
   fChain[ifile]->SetBranchAddress("u_sumet_el_medium_pfoEM", &u_sumet_el_medium_pfoEM, &b_u_sumet_el_medium_pfoEM);
   fChain[ifile]->SetBranchAddress("u_sumet_el_medium_pfoEMCentral", &u_sumet_el_medium_pfoEMCentral, &b_u_sumet_el_medium_pfoEMCentral);
   fChain[ifile]->SetBranchAddress("u_sumet_el_medium_pfoEMForward", &u_sumet_el_medium_pfoEMForward, &b_u_sumet_el_medium_pfoEMForward);
   fChain[ifile]->SetBranchAddress("u_sumet_el_medium_pfoNeutral", &u_sumet_el_medium_pfoNeutral, &b_u_sumet_el_medium_pfoNeutral);
   fChain[ifile]->SetBranchAddress("u_sumet_el_medium_pfoNeutralEM", &u_sumet_el_medium_pfoNeutralEM, &b_u_sumet_el_medium_pfoNeutralEM);
   fChain[ifile]->SetBranchAddress("u_sumet_el_medium_pfoNeutralEMCentral", &u_sumet_el_medium_pfoNeutralEMCentral, &b_u_sumet_el_medium_pfoNeutralEMCentral);
   fChain[ifile]->SetBranchAddress("u_sumet_el_medium_pfoNeutralEMForward", &u_sumet_el_medium_pfoNeutralEMForward, &b_u_sumet_el_medium_pfoNeutralEMForward);
   fChain[ifile]->SetBranchAddress("sumEt_loose", &sumEt_loose, &b_sumEt_loose);
   fChain[ifile]->SetBranchAddress("sumEtUE_loose", &sumEtUE_loose, &b_sumEtUE_loose);
   fChain[ifile]->SetBranchAddress("sumEt_medium", &sumEt_medium, &b_sumEt_medium);
   fChain[ifile]->SetBranchAddress("sumEtUE_mediumF", &sumEtUE_mediumF, &b_sumEtUE_medium);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_loose_pfoEM", &u_corrected_pt_el_loose_pfoEM, &b_u_corrected_pt_el_loose_pfoEM);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_loose_pfoEM", &u_corrected_phi_el_loose_pfoEM, &b_u_corrected_phi_el_loose_pfoEM);
   fChain[ifile]->SetBranchAddress("sumetweight_el_loose_pfoEM", &sumetweight_el_loose_pfoEM, &b_sumetweight_el_loose_pfoEM);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_medium_pfoEM", &u_corrected_pt_el_medium_pfoEM, &b_u_corrected_pt_el_medium_pfoEM);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_medium_pfoEM", &u_corrected_phi_el_medium_pfoEM, &b_u_corrected_phi_el_medium_pfoEM);
   fChain[ifile]->SetBranchAddress("sumetweight_el_medium_pfoEM", &sumetweight_el_medium_pfoEM, &b_sumetweight_el_medium_pfoEM);
   fChain[ifile]->SetBranchAddress("uParBoson", &uParBoson, &b_uParBoson);
   fChain[ifile]->SetBranchAddress("uPerpBoson", &uPerpBoson, &b_uPerpBoson);
   fChain[ifile]->SetBranchAddress("uParGenBoson", &uParGenBoson, &b_uParGenBoson);
   fChain[ifile]->SetBranchAddress("uPerpGenBoson", &uPerpGenBoson, &b_uPerpGenBoson);
   fChain[ifile]->SetBranchAddress("uParLepton", &uParLepton, &b_uParLepton);
   fChain[ifile]->SetBranchAddress("uPerpLepton", &uPerpLepton, &b_uPerpLepton);
   fChain[ifile]->SetBranchAddress("el_loose_u_ncones_removed", &el_loose_u_ncones_removed, &b_el_loose_u_ncones_removed);
   fChain[ifile]->SetBranchAddress("el_medium_u_ncones_removed", &el_medium_u_ncones_removed, &b_el_medium_u_ncones_removed);
   fChain[ifile]->SetBranchAddress("u_nPFO_charged", &u_nPFO_charged, &b_u_nPFO_charged);
   fChain[ifile]->SetBranchAddress("u_nPFO_neutral", &u_nPFO_neutral, &b_u_nPFO_neutral);
   fChain[ifile]->SetBranchAddress("incl_mu_pt", &incl_mu_pt, &b_incl_mu_pt);
   fChain[ifile]->SetBranchAddress("incl_mu_ptloss", &incl_mu_ptloss, &b_incl_mu_ptloss);
   fChain[ifile]->SetBranchAddress("incl_mu_eta", &incl_mu_eta, &b_incl_mu_eta);
   fChain[ifile]->SetBranchAddress("incl_mu_phi", &incl_mu_phi, &b_incl_mu_phi);
   fChain[ifile]->SetBranchAddress("incl_mu_d0sig", &incl_mu_d0sig, &b_incl_mu_d0sig);
   fChain[ifile]->SetBranchAddress("incl_mu_delta_z0", &incl_mu_delta_z0, &b_incl_mu_delta_z0);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_loose_pfoEM_RESOLUTION_STAT0_UP", &u_corrected_pt_el_loose_pfoEM_RESOLUTION_STAT0_UP, &b_u_corrected_pt_el_loose_pfoEM_RESOLUTION_STAT0_UP);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_loose_pfoEM_RESOLUTION_STAT0_UP", &u_corrected_phi_el_loose_pfoEM_RESOLUTION_STAT0_UP, &b_u_corrected_phi_el_loose_pfoEM_RESOLUTION_STAT0_UP);
   fChain[ifile]->SetBranchAddress("sumetweight_el_loose_pfoEM_RESOLUTION_STAT0_UP", &sumetweight_el_loose_pfoEM_RESOLUTION_STAT0_UP, &b_sumetweight_el_loose_pfoEM_RESOLUTION_STAT0_UP);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_loose_pfoEM_RESOLUTION_STAT0_DOWN", &u_corrected_pt_el_loose_pfoEM_RESOLUTION_STAT0_DOWN, &b_u_corrected_pt_el_loose_pfoEM_RESOLUTION_STAT0_DOWN);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_loose_pfoEM_RESOLUTION_STAT0_DOWN", &u_corrected_phi_el_loose_pfoEM_RESOLUTION_STAT0_DOWN, &b_u_corrected_phi_el_loose_pfoEM_RESOLUTION_STAT0_DOWN);
   fChain[ifile]->SetBranchAddress("sumetweight_el_loose_pfoEM_RESOLUTION_STAT0_DOWN", &sumetweight_el_loose_pfoEM_RESOLUTION_STAT0_DOWN, &b_sumetweight_el_loose_pfoEM_RESOLUTION_STAT0_DOWN);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_loose_pfoEM_RESOLUTION_STAT1_UP", &u_corrected_pt_el_loose_pfoEM_RESOLUTION_STAT1_UP, &b_u_corrected_pt_el_loose_pfoEM_RESOLUTION_STAT1_UP);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_loose_pfoEM_RESOLUTION_STAT1_UP", &u_corrected_phi_el_loose_pfoEM_RESOLUTION_STAT1_UP, &b_u_corrected_phi_el_loose_pfoEM_RESOLUTION_STAT1_UP);
   fChain[ifile]->SetBranchAddress("sumetweight_el_loose_pfoEM_RESOLUTION_STAT1_UP", &sumetweight_el_loose_pfoEM_RESOLUTION_STAT1_UP, &b_sumetweight_el_loose_pfoEM_RESOLUTION_STAT1_UP);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_loose_pfoEM_RESOLUTION_STAT1_DOWN", &u_corrected_pt_el_loose_pfoEM_RESOLUTION_STAT1_DOWN, &b_u_corrected_pt_el_loose_pfoEM_RESOLUTION_STAT1_DOWN);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_loose_pfoEM_RESOLUTION_STAT1_DOWN", &u_corrected_phi_el_loose_pfoEM_RESOLUTION_STAT1_DOWN, &b_u_corrected_phi_el_loose_pfoEM_RESOLUTION_STAT1_DOWN);
   fChain[ifile]->SetBranchAddress("sumetweight_el_loose_pfoEM_RESOLUTION_STAT1_DOWN", &sumetweight_el_loose_pfoEM_RESOLUTION_STAT1_DOWN, &b_sumetweight_el_loose_pfoEM_RESOLUTION_STAT1_DOWN);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_loose_pfoEM_RESPONSE_STAT0_UP", &u_corrected_pt_el_loose_pfoEM_RESPONSE_STAT0_UP, &b_u_corrected_pt_el_loose_pfoEM_RESPONSE_STAT0_UP);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_loose_pfoEM_RESPONSE_STAT0_UP", &u_corrected_phi_el_loose_pfoEM_RESPONSE_STAT0_UP, &b_u_corrected_phi_el_loose_pfoEM_RESPONSE_STAT0_UP);
   fChain[ifile]->SetBranchAddress("sumetweight_el_loose_pfoEM_RESPONSE_STAT0_UP", &sumetweight_el_loose_pfoEM_RESPONSE_STAT0_UP, &b_sumetweight_el_loose_pfoEM_RESPONSE_STAT0_UP);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_loose_pfoEM_RESPONSE_STAT0_DOWN", &u_corrected_pt_el_loose_pfoEM_RESPONSE_STAT0_DOWN, &b_u_corrected_pt_el_loose_pfoEM_RESPONSE_STAT0_DOWN);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_loose_pfoEM_RESPONSE_STAT0_DOWN", &u_corrected_phi_el_loose_pfoEM_RESPONSE_STAT0_DOWN, &b_u_corrected_phi_el_loose_pfoEM_RESPONSE_STAT0_DOWN);
   fChain[ifile]->SetBranchAddress("sumetweight_el_loose_pfoEM_RESPONSE_STAT0_DOWN", &sumetweight_el_loose_pfoEM_RESPONSE_STAT0_DOWN, &b_sumetweight_el_loose_pfoEM_RESPONSE_STAT0_DOWN);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_loose_pfoEM_RESPONSE_STAT1_UP", &u_corrected_pt_el_loose_pfoEM_RESPONSE_STAT1_UP, &b_u_corrected_pt_el_loose_pfoEM_RESPONSE_STAT1_UP);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_loose_pfoEM_RESPONSE_STAT1_UP", &u_corrected_phi_el_loose_pfoEM_RESPONSE_STAT1_UP, &b_u_corrected_phi_el_loose_pfoEM_RESPONSE_STAT1_UP);
   fChain[ifile]->SetBranchAddress("sumetweight_el_loose_pfoEM_RESPONSE_STAT1_UP", &sumetweight_el_loose_pfoEM_RESPONSE_STAT1_UP, &b_sumetweight_el_loose_pfoEM_RESPONSE_STAT1_UP);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_loose_pfoEM_RESPONSE_STAT1_DOWN", &u_corrected_pt_el_loose_pfoEM_RESPONSE_STAT1_DOWN, &b_u_corrected_pt_el_loose_pfoEM_RESPONSE_STAT1_DOWN);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_loose_pfoEM_RESPONSE_STAT1_DOWN", &u_corrected_phi_el_loose_pfoEM_RESPONSE_STAT1_DOWN, &b_u_corrected_phi_el_loose_pfoEM_RESPONSE_STAT1_DOWN);
   fChain[ifile]->SetBranchAddress("sumetweight_el_loose_pfoEM_RESPONSE_STAT1_DOWN", &sumetweight_el_loose_pfoEM_RESPONSE_STAT1_DOWN, &b_sumetweight_el_loose_pfoEM_RESPONSE_STAT1_DOWN);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_medium_pfoEM_RESOLUTION_STAT0_UP", &u_corrected_pt_el_medium_pfoEM_RESOLUTION_STAT0_UP, &b_u_corrected_pt_el_medium_pfoEM_RESOLUTION_STAT0_UP);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_medium_pfoEM_RESOLUTION_STAT0_UP", &u_corrected_phi_el_medium_pfoEM_RESOLUTION_STAT0_UP, &b_u_corrected_phi_el_medium_pfoEM_RESOLUTION_STAT0_UP);
   fChain[ifile]->SetBranchAddress("sumetweight_el_medium_pfoEM_RESOLUTION_STAT0_UP", &sumetweight_el_medium_pfoEM_RESOLUTION_STAT0_UP, &b_sumetweight_el_medium_pfoEM_RESOLUTION_STAT0_UP);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_medium_pfoEM_RESOLUTION_STAT0_DOWN", &u_corrected_pt_el_medium_pfoEM_RESOLUTION_STAT0_DOWN, &b_u_corrected_pt_el_medium_pfoEM_RESOLUTION_STAT0_DOWN);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_medium_pfoEM_RESOLUTION_STAT0_DOWN", &u_corrected_phi_el_medium_pfoEM_RESOLUTION_STAT0_DOWN, &b_u_corrected_phi_el_medium_pfoEM_RESOLUTION_STAT0_DOWN);
   fChain[ifile]->SetBranchAddress("sumetweight_el_medium_pfoEM_RESOLUTION_STAT0_DOWN", &sumetweight_el_medium_pfoEM_RESOLUTION_STAT0_DOWN, &b_sumetweight_el_medium_pfoEM_RESOLUTION_STAT0_DOWN);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_medium_pfoEM_RESOLUTION_STAT1_UP", &u_corrected_pt_el_medium_pfoEM_RESOLUTION_STAT1_UP, &b_u_corrected_pt_el_medium_pfoEM_RESOLUTION_STAT1_UP);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_medium_pfoEM_RESOLUTION_STAT1_UP", &u_corrected_phi_el_medium_pfoEM_RESOLUTION_STAT1_UP, &b_u_corrected_phi_el_medium_pfoEM_RESOLUTION_STAT1_UP);
   fChain[ifile]->SetBranchAddress("sumetweight_el_medium_pfoEM_RESOLUTION_STAT1_UP", &sumetweight_el_medium_pfoEM_RESOLUTION_STAT1_UP, &b_sumetweight_el_medium_pfoEM_RESOLUTION_STAT1_UP);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_medium_pfoEM_RESOLUTION_STAT1_DOWN", &u_corrected_pt_el_medium_pfoEM_RESOLUTION_STAT1_DOWN, &b_u_corrected_pt_el_medium_pfoEM_RESOLUTION_STAT1_DOWN);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_medium_pfoEM_RESOLUTION_STAT1_DOWN", &u_corrected_phi_el_medium_pfoEM_RESOLUTION_STAT1_DOWN, &b_u_corrected_phi_el_medium_pfoEM_RESOLUTION_STAT1_DOWN);
   fChain[ifile]->SetBranchAddress("sumetweight_el_medium_pfoEM_RESOLUTION_STAT1_DOWN", &sumetweight_el_medium_pfoEM_RESOLUTION_STAT1_DOWN, &b_sumetweight_el_medium_pfoEM_RESOLUTION_STAT1_DOWN);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_medium_pfoEM_RESPONSE_STAT0_UP", &u_corrected_pt_el_medium_pfoEM_RESPONSE_STAT0_UP, &b_u_corrected_pt_el_medium_pfoEM_RESPONSE_STAT0_UP);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_medium_pfoEM_RESPONSE_STAT0_UP", &u_corrected_phi_el_medium_pfoEM_RESPONSE_STAT0_UP, &b_u_corrected_phi_el_medium_pfoEM_RESPONSE_STAT0_UP);
   fChain[ifile]->SetBranchAddress("sumetweight_el_medium_pfoEM_RESPONSE_STAT0_UP", &sumetweight_el_medium_pfoEM_RESPONSE_STAT0_UP, &b_sumetweight_el_medium_pfoEM_RESPONSE_STAT0_UP);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_medium_pfoEM_RESPONSE_STAT0_DOWN", &u_corrected_pt_el_medium_pfoEM_RESPONSE_STAT0_DOWN, &b_u_corrected_pt_el_medium_pfoEM_RESPONSE_STAT0_DOWN);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_medium_pfoEM_RESPONSE_STAT0_DOWN", &u_corrected_phi_el_medium_pfoEM_RESPONSE_STAT0_DOWN, &b_u_corrected_phi_el_medium_pfoEM_RESPONSE_STAT0_DOWN);
   fChain[ifile]->SetBranchAddress("sumetweight_el_medium_pfoEM_RESPONSE_STAT0_DOWN", &sumetweight_el_medium_pfoEM_RESPONSE_STAT0_DOWN, &b_sumetweight_el_medium_pfoEM_RESPONSE_STAT0_DOWN);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_medium_pfoEM_RESPONSE_STAT1_UP", &u_corrected_pt_el_medium_pfoEM_RESPONSE_STAT1_UP, &b_u_corrected_pt_el_medium_pfoEM_RESPONSE_STAT1_UP);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_medium_pfoEM_RESPONSE_STAT1_UP", &u_corrected_phi_el_medium_pfoEM_RESPONSE_STAT1_UP, &b_u_corrected_phi_el_medium_pfoEM_RESPONSE_STAT1_UP);
   fChain[ifile]->SetBranchAddress("sumetweight_el_medium_pfoEM_RESPONSE_STAT1_UP", &sumetweight_el_medium_pfoEM_RESPONSE_STAT1_UP, &b_sumetweight_el_medium_pfoEM_RESPONSE_STAT1_UP);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_medium_pfoEM_RESPONSE_STAT1_DOWN", &u_corrected_pt_el_medium_pfoEM_RESPONSE_STAT1_DOWN, &b_u_corrected_pt_el_medium_pfoEM_RESPONSE_STAT1_DOWN);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_medium_pfoEM_RESPONSE_STAT1_DOWN", &u_corrected_phi_el_medium_pfoEM_RESPONSE_STAT1_DOWN, &b_u_corrected_phi_el_medium_pfoEM_RESPONSE_STAT1_DOWN);
   fChain[ifile]->SetBranchAddress("sumetweight_el_medium_pfoEM_RESPONSE_STAT1_DOWN", &sumetweight_el_medium_pfoEM_RESPONSE_STAT1_DOWN, &b_sumetweight_el_medium_pfoEM_RESPONSE_STAT1_DOWN);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_loose_pfoEM_RESOLUTION_EXTSYS_UP", &u_corrected_pt_el_loose_pfoEM_RESOLUTION_EXTSYS_UP, &b_u_corrected_pt_el_loose_pfoEM_RESOLUTION_EXTSYS_UP);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_loose_pfoEM_RESOLUTION_EXTSYS_UP", &u_corrected_phi_el_loose_pfoEM_RESOLUTION_EXTSYS_UP, &b_u_corrected_phi_el_loose_pfoEM_RESOLUTION_EXTSYS_UP);
   fChain[ifile]->SetBranchAddress("sumetweight_el_loose_pfoEM_RESOLUTION_EXTSYS_UP", &sumetweight_el_loose_pfoEM_RESOLUTION_EXTSYS_UP, &b_sumetweight_el_loose_pfoEM_RESOLUTION_EXTSYS_UP);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_loose_pfoEM_RESOLUTION_EXTSYS_DOWN", &u_corrected_pt_el_loose_pfoEM_RESOLUTION_EXTSYS_DOWN, &b_u_corrected_pt_el_loose_pfoEM_RESOLUTION_EXTSYS_DOWN);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_loose_pfoEM_RESOLUTION_EXTSYS_DOWN", &u_corrected_phi_el_loose_pfoEM_RESOLUTION_EXTSYS_DOWN, &b_u_corrected_phi_el_loose_pfoEM_RESOLUTION_EXTSYS_DOWN);
   fChain[ifile]->SetBranchAddress("sumetweight_el_loose_pfoEM_RESOLUTION_EXTSYS_DOWN", &sumetweight_el_loose_pfoEM_RESOLUTION_EXTSYS_DOWN, &b_sumetweight_el_loose_pfoEM_RESOLUTION_EXTSYS_DOWN);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_loose_pfoEM_RESPONSE_EXTSYS_UP", &u_corrected_pt_el_loose_pfoEM_RESPONSE_EXTSYS_UP, &b_u_corrected_pt_el_loose_pfoEM_RESPONSE_EXTSYS_UP);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_loose_pfoEM_RESPONSE_EXTSYS_UP", &u_corrected_phi_el_loose_pfoEM_RESPONSE_EXTSYS_UP, &b_u_corrected_phi_el_loose_pfoEM_RESPONSE_EXTSYS_UP);
   fChain[ifile]->SetBranchAddress("sumetweight_el_loose_pfoEM_RESPONSE_EXTSYS_UP", &sumetweight_el_loose_pfoEM_RESPONSE_EXTSYS_UP, &b_sumetweight_el_loose_pfoEM_RESPONSE_EXTSYS_UP);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_loose_pfoEM_RESPONSE_EXTSYS_DOWN", &u_corrected_pt_el_loose_pfoEM_RESPONSE_EXTSYS_DOWN, &b_u_corrected_pt_el_loose_pfoEM_RESPONSE_EXTSYS_DOWN);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_loose_pfoEM_RESPONSE_EXTSYS_DOWN", &u_corrected_phi_el_loose_pfoEM_RESPONSE_EXTSYS_DOWN, &b_u_corrected_phi_el_loose_pfoEM_RESPONSE_EXTSYS_DOWN);
   fChain[ifile]->SetBranchAddress("sumetweight_el_loose_pfoEM_RESPONSE_EXTSYS_DOWN", &sumetweight_el_loose_pfoEM_RESPONSE_EXTSYS_DOWN, &b_sumetweight_el_loose_pfoEM_RESPONSE_EXTSYS_DOWN);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_loose_pfoEM_RESPONSE_SYS_UP", &u_corrected_pt_el_loose_pfoEM_RESPONSE_SYS_UP, &b_u_corrected_pt_el_loose_pfoEM_RESPONSE_SYS_UP);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_loose_pfoEM_RESPONSE_SYS_UP", &u_corrected_phi_el_loose_pfoEM_RESPONSE_SYS_UP, &b_u_corrected_phi_el_loose_pfoEM_RESPONSE_SYS_UP);
   fChain[ifile]->SetBranchAddress("sumetweight_el_loose_pfoEM_RESPONSE_SYS_UP", &sumetweight_el_loose_pfoEM_RESPONSE_SYS_UP, &b_sumetweight_el_loose_pfoEM_RESPONSE_SYS_UP);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_loose_pfoEM_RESPONSE_SYS_DOWN", &u_corrected_pt_el_loose_pfoEM_RESPONSE_SYS_DOWN, &b_u_corrected_pt_el_loose_pfoEM_RESPONSE_SYS_DOWN);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_loose_pfoEM_RESPONSE_SYS_DOWN", &u_corrected_phi_el_loose_pfoEM_RESPONSE_SYS_DOWN, &b_u_corrected_phi_el_loose_pfoEM_RESPONSE_SYS_DOWN);
   fChain[ifile]->SetBranchAddress("sumetweight_el_loose_pfoEM_RESPONSE_SYS_DOWN", &sumetweight_el_loose_pfoEM_RESPONSE_SYS_DOWN, &b_sumetweight_el_loose_pfoEM_RESPONSE_SYS_DOWN);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_loose_pfoEM_SET_SYS", &u_corrected_pt_el_loose_pfoEM_SET_SYS, &b_u_corrected_pt_el_loose_pfoEM_SET_SYS);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_loose_pfoEM_SET_SYS", &u_corrected_phi_el_loose_pfoEM_SET_SYS, &b_u_corrected_phi_el_loose_pfoEM_SET_SYS);
   fChain[ifile]->SetBranchAddress("sumetweight_el_loose_pfoEM_SET_SYS", &sumetweight_el_loose_pfoEM_SET_SYS, &b_sumetweight_el_loose_pfoEM_SET_SYS);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_medium_pfoEM_RESOLUTION_EXTSYS_UP", &u_corrected_pt_el_medium_pfoEM_RESOLUTION_EXTSYS_UP, &b_u_corrected_pt_el_medium_pfoEM_RESOLUTION_EXTSYS_UP);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_medium_pfoEM_RESOLUTION_EXTSYS_UP", &u_corrected_phi_el_medium_pfoEM_RESOLUTION_EXTSYS_UP, &b_u_corrected_phi_el_medium_pfoEM_RESOLUTION_EXTSYS_UP);
   fChain[ifile]->SetBranchAddress("sumetweight_el_medium_pfoEM_RESOLUTION_EXTSYS_UP", &sumetweight_el_medium_pfoEM_RESOLUTION_EXTSYS_UP, &b_sumetweight_el_medium_pfoEM_RESOLUTION_EXTSYS_UP);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_medium_pfoEM_RESOLUTION_EXTSYS_DOWN", &u_corrected_pt_el_medium_pfoEM_RESOLUTION_EXTSYS_DOWN, &b_u_corrected_pt_el_medium_pfoEM_RESOLUTION_EXTSYS_DOWN);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_medium_pfoEM_RESOLUTION_EXTSYS_DOWN", &u_corrected_phi_el_medium_pfoEM_RESOLUTION_EXTSYS_DOWN, &b_u_corrected_phi_el_medium_pfoEM_RESOLUTION_EXTSYS_DOWN);
   fChain[ifile]->SetBranchAddress("sumetweight_el_medium_pfoEM_RESOLUTION_EXTSYS_DOWN", &sumetweight_el_medium_pfoEM_RESOLUTION_EXTSYS_DOWN, &b_sumetweight_el_medium_pfoEM_RESOLUTION_EXTSYS_DOWN);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_medium_pfoEM_RESPONSE_EXTSYS_UP", &u_corrected_pt_el_medium_pfoEM_RESPONSE_EXTSYS_UP, &b_u_corrected_pt_el_medium_pfoEM_RESPONSE_EXTSYS_UP);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_medium_pfoEM_RESPONSE_EXTSYS_UP", &u_corrected_phi_el_medium_pfoEM_RESPONSE_EXTSYS_UP, &b_u_corrected_phi_el_medium_pfoEM_RESPONSE_EXTSYS_UP);
   fChain[ifile]->SetBranchAddress("sumetweight_el_medium_pfoEM_RESPONSE_EXTSYS_UP", &sumetweight_el_medium_pfoEM_RESPONSE_EXTSYS_UP, &b_sumetweight_el_medium_pfoEM_RESPONSE_EXTSYS_UP);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_medium_pfoEM_RESPONSE_EXTSYS_DOWN", &u_corrected_pt_el_medium_pfoEM_RESPONSE_EXTSYS_DOWN, &b_u_corrected_pt_el_medium_pfoEM_RESPONSE_EXTSYS_DOWN);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_medium_pfoEM_RESPONSE_EXTSYS_DOWN", &u_corrected_phi_el_medium_pfoEM_RESPONSE_EXTSYS_DOWN, &b_u_corrected_phi_el_medium_pfoEM_RESPONSE_EXTSYS_DOWN);
   fChain[ifile]->SetBranchAddress("sumetweight_el_medium_pfoEM_RESPONSE_EXTSYS_DOWN", &sumetweight_el_medium_pfoEM_RESPONSE_EXTSYS_DOWN, &b_sumetweight_el_medium_pfoEM_RESPONSE_EXTSYS_DOWN);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_medium_pfoEM_RESPONSE_SYS_UP", &u_corrected_pt_el_medium_pfoEM_RESPONSE_SYS_UP, &b_u_corrected_pt_el_medium_pfoEM_RESPONSE_SYS_UP);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_medium_pfoEM_RESPONSE_SYS_UP", &u_corrected_phi_el_medium_pfoEM_RESPONSE_SYS_UP, &b_u_corrected_phi_el_medium_pfoEM_RESPONSE_SYS_UP);
   fChain[ifile]->SetBranchAddress("sumetweight_el_medium_pfoEM_RESPONSE_SYS_UP", &sumetweight_el_medium_pfoEM_RESPONSE_SYS_UP, &b_sumetweight_el_medium_pfoEM_RESPONSE_SYS_UP);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_medium_pfoEM_RESPONSE_SYS_DOWN", &u_corrected_pt_el_medium_pfoEM_RESPONSE_SYS_DOWN, &b_u_corrected_pt_el_medium_pfoEM_RESPONSE_SYS_DOWN);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_medium_pfoEM_RESPONSE_SYS_DOWN", &u_corrected_phi_el_medium_pfoEM_RESPONSE_SYS_DOWN, &b_u_corrected_phi_el_medium_pfoEM_RESPONSE_SYS_DOWN);
   fChain[ifile]->SetBranchAddress("sumetweight_el_medium_pfoEM_RESPONSE_SYS_DOWN", &sumetweight_el_medium_pfoEM_RESPONSE_SYS_DOWN, &b_sumetweight_el_medium_pfoEM_RESPONSE_SYS_DOWN);
   fChain[ifile]->SetBranchAddress("u_corrected_pt_el_medium_pfoEM_SET_SYS", &u_corrected_pt_el_medium_pfoEM_SET_SYS, &b_u_corrected_pt_el_medium_pfoEM_SET_SYS);
   fChain[ifile]->SetBranchAddress("u_corrected_phi_el_medium_pfoEM_SET_SYS", &u_corrected_phi_el_medium_pfoEM_SET_SYS, &b_u_corrected_phi_el_medium_pfoEM_SET_SYS);
   fChain[ifile]->SetBranchAddress("sumetweight_el_medium_pfoEM_SET_SYS", &sumetweight_el_medium_pfoEM_SET_SYS, &b_sumetweight_el_medium_pfoEM_SET_SYS);
   fChain[ifile]->SetBranchAddress("tu_pt_Int", &tu_pt_Int, &b_tu_pt_Int);
   fChain[ifile]->SetBranchAddress("tu_pt_IntMuons", &tu_pt_IntMuons, &b_tu_pt_IntMuons);
   fChain[ifile]->SetBranchAddress("tu_pt_IntOut", &tu_pt_IntOut, &b_tu_pt_IntOut);
   fChain[ifile]->SetBranchAddress("tu_pt_NonInt", &tu_pt_NonInt, &b_tu_pt_NonInt);
   fChain[ifile]->SetBranchAddress("tu_phi_Int", &tu_phi_Int, &b_tu_phi_Int);
   fChain[ifile]->SetBranchAddress("tu_phi_IntMuons", &tu_phi_IntMuons, &b_tu_phi_IntMuons);
   fChain[ifile]->SetBranchAddress("tu_phi_IntOut", &tu_phi_IntOut, &b_tu_phi_IntOut);
   fChain[ifile]->SetBranchAddress("tu_phi_NonInt", &tu_phi_NonInt, &b_tu_phi_NonInt);
   fChain[ifile]->SetBranchAddress("tu_sumet_Int", &tu_sumet_Int, &b_tu_sumet_Int);
   fChain[ifile]->SetBranchAddress("tu_sumet_IntMuons", &tu_sumet_IntMuons, &b_tu_sumet_IntMuons);
   fChain[ifile]->SetBranchAddress("tu_sumet_IntOut", &tu_sumet_IntOut, &b_tu_sumet_IntOut);
   fChain[ifile]->SetBranchAddress("tu_sumet_NonInt", &tu_sumet_NonInt, &b_tu_sumet_NonInt);
   fChain[ifile]->SetBranchAddress("tlep_dressed_pt", &tlep_dressed_pt, &b_tlep_dressed_pt);
   fChain[ifile]->SetBranchAddress("tlep_dressed_eta", &tlep_dressed_eta, &b_tlep_dressed_eta);
   fChain[ifile]->SetBranchAddress("tlep_dressed_phi", &tlep_dressed_phi, &b_tlep_dressed_phi);
   fChain[ifile]->SetBranchAddress("tlep_dressed_e", &tlep_dressed_e, &b_tlep_dressed_e);
   fChain[ifile]->SetBranchAddress("tlep_dressed_pdgId", &tlep_dressed_pdgId, &b_tlep_dressed_pdgId);
   fChain[ifile]->SetBranchAddress("tlep_bare_pt", &tlep_bare_pt, &b_tlep_bare_pt);
   fChain[ifile]->SetBranchAddress("tlep_bare_eta", &tlep_bare_eta, &b_tlep_bare_eta);
   fChain[ifile]->SetBranchAddress("tlep_bare_phi", &tlep_bare_phi, &b_tlep_bare_phi);
   fChain[ifile]->SetBranchAddress("tlep_bare_e", &tlep_bare_e, &b_tlep_bare_e);
   fChain[ifile]->SetBranchAddress("tlep_bare_pdgId", &tlep_bare_pdgId, &b_tlep_bare_pdgId);
   fChain[ifile]->SetBranchAddress("tlep_born_pt", &tlep_born_pt, &b_tlep_born_pt);
   fChain[ifile]->SetBranchAddress("tlep_born_eta", &tlep_born_eta, &b_tlep_born_eta);
   fChain[ifile]->SetBranchAddress("tlep_born_phi", &tlep_born_phi, &b_tlep_born_phi);
   fChain[ifile]->SetBranchAddress("tlep_born_e", &tlep_born_e, &b_tlep_born_e);
   fChain[ifile]->SetBranchAddress("tlep_born_pdgId", &tlep_born_pdgId, &b_tlep_born_pdgId);
   fChain[ifile]->SetBranchAddress("tneutrino_pt", &tneutrino_pt, &b_tneutrino_pt);
   fChain[ifile]->SetBranchAddress("tneutrino_eta", &tneutrino_eta, &b_tneutrino_eta);
   fChain[ifile]->SetBranchAddress("tneutrino_phi", &tneutrino_phi, &b_tneutrino_phi);
   fChain[ifile]->SetBranchAddress("tneutrino_e", &tneutrino_e, &b_tneutrino_e);
   fChain[ifile]->SetBranchAddress("tneutrino_pdgId", &tneutrino_pdgId, &b_tneutrino_pdgId);
   fChain[ifile]->SetBranchAddress("tbornneutrino_pt", &tbornneutrino_pt, &b_tbornneutrino_pt);
   fChain[ifile]->SetBranchAddress("tbornneutrino_eta", &tbornneutrino_eta, &b_tbornneutrino_eta);
   fChain[ifile]->SetBranchAddress("tbornneutrino_phi", &tbornneutrino_phi, &b_tbornneutrino_phi);
   fChain[ifile]->SetBranchAddress("tbornneutrino_e", &tbornneutrino_e, &b_tbornneutrino_e);
   fChain[ifile]->SetBranchAddress("tbornneutrino_pdgId", &tbornneutrino_pdgId, &b_tbornneutrino_pdgId);
   fChain[ifile]->SetBranchAddress("tphoton_pt", &tphoton_pt, &b_tphoton_pt);
   fChain[ifile]->SetBranchAddress("tphoton_eta", &tphoton_eta, &b_tphoton_eta);
   fChain[ifile]->SetBranchAddress("tphoton_phi", &tphoton_phi, &b_tphoton_phi);
   fChain[ifile]->SetBranchAddress("tphoton_e", &tphoton_e, &b_tphoton_e);
   fChain[ifile]->SetBranchAddress("tjet_pt", &tjet_pt, &b_tjet_pt);
   fChain[ifile]->SetBranchAddress("tjet_eta", &tjet_eta, &b_tjet_eta);
   fChain[ifile]->SetBranchAddress("tjet_phi", &tjet_phi, &b_tjet_phi);
   fChain[ifile]->SetBranchAddress("tjet_e", &tjet_e, &b_tjet_e);
   fChain[ifile]->SetBranchAddress("tboson_pt", &tboson_pt, &b_tboson_pt);
   fChain[ifile]->SetBranchAddress("tboson_eta", &tboson_eta, &b_tboson_eta);
   fChain[ifile]->SetBranchAddress("tboson_phi", &tboson_phi, &b_tboson_phi);
   fChain[ifile]->SetBranchAddress("tboson_e", &tboson_e, &b_tboson_e);
   fChain[ifile]->SetBranchAddress("tboson_pdgId", &tboson_pdgId, &b_tboson_pdgId);
   fChain[ifile]->SetBranchAddress("tparton_pdgId1", &tparton_pdgId1, &b_tparton_pdgId1);
   fChain[ifile]->SetBranchAddress("tparton_pdgId2", &tparton_pdgId2, &b_tparton_pdgId2);

   TotalEntries[ifile] = fChain[ifile]->GetEntries();
}

void TreeForWasym::GetEntry(int ifile, int i)
{
 fChain[ifile]->GetEntry(i);
}
