# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _PyePump
else:
    import _PyePump

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _PyePump.delete_SwigPyIterator

    def value(self):
        return _PyePump.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _PyePump.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _PyePump.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _PyePump.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _PyePump.SwigPyIterator_equal(self, x)

    def copy(self):
        return _PyePump.SwigPyIterator_copy(self)

    def next(self):
        return _PyePump.SwigPyIterator_next(self)

    def __next__(self):
        return _PyePump.SwigPyIterator___next__(self)

    def previous(self):
        return _PyePump.SwigPyIterator_previous(self)

    def advance(self, n):
        return _PyePump.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _PyePump.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _PyePump.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _PyePump.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _PyePump.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _PyePump.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _PyePump.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _PyePump:
_PyePump.SwigPyIterator_swigregister(SwigPyIterator)
class DoubleVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _PyePump.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _PyePump.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _PyePump.DoubleVector___bool__(self)

    def __len__(self):
        return _PyePump.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _PyePump.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _PyePump.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _PyePump.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _PyePump.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _PyePump.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _PyePump.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _PyePump.DoubleVector_pop(self)

    def append(self, x):
        return _PyePump.DoubleVector_append(self, x)

    def empty(self):
        return _PyePump.DoubleVector_empty(self)

    def size(self):
        return _PyePump.DoubleVector_size(self)

    def swap(self, v):
        return _PyePump.DoubleVector_swap(self, v)

    def begin(self):
        return _PyePump.DoubleVector_begin(self)

    def end(self):
        return _PyePump.DoubleVector_end(self)

    def rbegin(self):
        return _PyePump.DoubleVector_rbegin(self)

    def rend(self):
        return _PyePump.DoubleVector_rend(self)

    def clear(self):
        return _PyePump.DoubleVector_clear(self)

    def get_allocator(self):
        return _PyePump.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _PyePump.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _PyePump.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        _PyePump.DoubleVector_swiginit(self, _PyePump.new_DoubleVector(*args))

    def push_back(self, x):
        return _PyePump.DoubleVector_push_back(self, x)

    def front(self):
        return _PyePump.DoubleVector_front(self)

    def back(self):
        return _PyePump.DoubleVector_back(self)

    def assign(self, n, x):
        return _PyePump.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _PyePump.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _PyePump.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _PyePump.DoubleVector_reserve(self, n)

    def capacity(self):
        return _PyePump.DoubleVector_capacity(self)
    __swig_destroy__ = _PyePump.delete_DoubleVector

# Register DoubleVector in _PyePump:
_PyePump.DoubleVector_swigregister(DoubleVector)
class StringVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _PyePump.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _PyePump.StringVector___nonzero__(self)

    def __bool__(self):
        return _PyePump.StringVector___bool__(self)

    def __len__(self):
        return _PyePump.StringVector___len__(self)

    def __getslice__(self, i, j):
        return _PyePump.StringVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _PyePump.StringVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _PyePump.StringVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _PyePump.StringVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _PyePump.StringVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _PyePump.StringVector___setitem__(self, *args)

    def pop(self):
        return _PyePump.StringVector_pop(self)

    def append(self, x):
        return _PyePump.StringVector_append(self, x)

    def empty(self):
        return _PyePump.StringVector_empty(self)

    def size(self):
        return _PyePump.StringVector_size(self)

    def swap(self, v):
        return _PyePump.StringVector_swap(self, v)

    def begin(self):
        return _PyePump.StringVector_begin(self)

    def end(self):
        return _PyePump.StringVector_end(self)

    def rbegin(self):
        return _PyePump.StringVector_rbegin(self)

    def rend(self):
        return _PyePump.StringVector_rend(self)

    def clear(self):
        return _PyePump.StringVector_clear(self)

    def get_allocator(self):
        return _PyePump.StringVector_get_allocator(self)

    def pop_back(self):
        return _PyePump.StringVector_pop_back(self)

    def erase(self, *args):
        return _PyePump.StringVector_erase(self, *args)

    def __init__(self, *args):
        _PyePump.StringVector_swiginit(self, _PyePump.new_StringVector(*args))

    def push_back(self, x):
        return _PyePump.StringVector_push_back(self, x)

    def front(self):
        return _PyePump.StringVector_front(self)

    def back(self):
        return _PyePump.StringVector_back(self)

    def assign(self, n, x):
        return _PyePump.StringVector_assign(self, n, x)

    def resize(self, *args):
        return _PyePump.StringVector_resize(self, *args)

    def insert(self, *args):
        return _PyePump.StringVector_insert(self, *args)

    def reserve(self, n):
        return _PyePump.StringVector_reserve(self, n)

    def capacity(self):
        return _PyePump.StringVector_capacity(self)
    __swig_destroy__ = _PyePump.delete_StringVector

# Register StringVector in _PyePump:
_PyePump.StringVector_swigregister(StringVector)
class PyePump(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    EU = property(_PyePump.PyePump_EU_get, _PyePump.PyePump_EU_set)
    isUpdatePDFOnly = property(_PyePump.PyePump_isUpdatePDFOnly_get, _PyePump.PyePump_isUpdatePDFOnly_set)
    writefile = property(_PyePump.PyePump_writefile_get, _PyePump.PyePump_writefile_set)
    doCorrelationCosine = property(_PyePump.PyePump_doCorrelationCosine_get, _PyePump.PyePump_doCorrelationCosine_set)

    def __init__(self):
        _PyePump.PyePump_swiginit(self, _PyePump.new_PyePump())
    __swig_destroy__ = _PyePump.delete_PyePump

    def Initialize(self, name):
        return _PyePump.PyePump_Initialize(self, name)

    def Update(self):
        return _PyePump.PyePump_Update(self)

    def UpdateAlphaS(self, name):
        return _PyePump.PyePump_UpdateAlphaS(self, name)

    def UpdateParameter(self, name):
        return _PyePump.PyePump_UpdateParameter(self, name)

    def InputLMScanDrawList(self, list):
        return _PyePump.PyePump_InputLMScanDrawList(self, list)

    def PDFLMScanModule(self, flavor, x, Q, isUpdate):
        return _PyePump.PyePump_PDFLMScanModule(self, flavor, x, Q, isUpdate)

    def LMScanModule(self, name, iPoint, isUpdate, legend):
        return _PyePump.PyePump_LMScanModule(self, name, iPoint, isUpdate, legend)

    def UpdateAlphaSLMScanPDF(self, flavor, x, Q):
        return _PyePump.PyePump_UpdateAlphaSLMScanPDF(self, flavor, x, Q)

    def UpdateAlphaSLMScanObservable(self, name, iPoint, legend):
        return _PyePump.PyePump_UpdateAlphaSLMScanObservable(self, name, iPoint, legend)

    def AlphaSObservableCorrelation(self, name, iPoint, legend):
        return _PyePump.PyePump_AlphaSObservableCorrelation(self, name, iPoint, legend)

    def InputL2SensitivityDrawList(self, list):
        return _PyePump.PyePump_InputL2SensitivityDrawList(self, list)

    def DrawL2Sensitivity(self, flavor, x, Q, isUpdate):
        return _PyePump.PyePump_DrawL2Sensitivity(self, flavor, x, Q, isUpdate)

    def SetLegend(self, name, legend):
        return _PyePump.PyePump_SetLegend(self, name, legend)

    def TurnOnCorrelationCosine(self):
        return _PyePump.PyePump_TurnOnCorrelationCosine(self)

    def GetOldTheory(self, DataName, i):
        return _PyePump.PyePump_GetOldTheory(self, DataName, i)

    def GetNewTheory(self, DataName, i):
        return _PyePump.PyePump_GetNewTheory(self, DataName, i)

    def GetOldPDFError(self, DataName, i):
        return _PyePump.PyePump_GetOldPDFError(self, DataName, i)

    def GetNewPDFError(self, DataName, i):
        return _PyePump.PyePump_GetNewPDFError(self, DataName, i)

    def GetOldPDFCorrelation(self, DataName1, DataName2, i, j):
        return _PyePump.PyePump_GetOldPDFCorrelation(self, DataName1, DataName2, i, j)

    def GetNewPDFCorrelation(self, DataName1, DataName2, i, j):
        return _PyePump.PyePump_GetNewPDFCorrelation(self, DataName1, DataName2, i, j)

    def GetOldChi2(self, DataName):
        return _PyePump.PyePump_GetOldChi2(self, DataName)

    def GetNewChi2(self, DataName):
        return _PyePump.PyePump_GetNewChi2(self, DataName)

    def GetOldAlphaS(self):
        return _PyePump.PyePump_GetOldAlphaS(self)

    def GetNewAlphaS(self):
        return _PyePump.PyePump_GetNewAlphaS(self)

    def GetOldAlphaSError(self):
        return _PyePump.PyePump_GetOldAlphaSError(self)

    def GetNewAlphaSError(self):
        return _PyePump.PyePump_GetNewAlphaSError(self)

# Register PyePump in _PyePump:
_PyePump.PyePump_swigregister(PyePump)

